Add TCP TPROXY support
Dreamacro/clash pull request #1049
Opened 2020-10-29 08:53 UTC by maskedeken

增加TCP TPROXY支持。

在配置文件中增加tproxy: true，可以启用TCP TPROXY

样例：
redir-port: 7892
port: 7890
socks-port: 7891
ipv6: false
mode: rule
log-level: debug
external-controller: 0.0.0.0:9090
secret: "123456"
allow-lan: true
tproxy: true

2020-11-02 05:30 UTC, Dreamacro commented
不如这样吧

```yaml
# redir-port 继续用着 redirect tcp + tproxy udp
redir-port: 7892

# tproxy-port 使用 tproxy tcp + tproxy udp
tproxy-port: 7893
```

2020-11-02 06:36 UTC, maskedeken commented
> 
> 
> 不如这样吧
> 
> ```yaml
> # redir-port 继续用着 redirect tcp + tproxy udp
> redir-port: 7892
> 
> # tproxy-port 使用 tproxy tcp + tproxy udp
> tproxy-port: 7893
> ```

As you wish

2020-11-05 03:17 UTC, h0cheung commented
对 ipv6 流量的转发正常吗

2020-11-05 07:51 UTC, maskedeken commented
> 
> 
> 对 ipv6 流量的转发正常吗

TProxy应该是支持ipv6的

2020-11-06 10:04 UTC, Dreamacro requested changes

2020-11-06 10:04 UTC, Dreamacro commented on proxy/redir/tproxy.go
> +	rl := &TProxyListener{Listener: l,
plz format this

2020-11-06 10:04 UTC, Dreamacro commented on proxy/redir/tproxy.go
> +	tunnel.Add(inbound.NewSocket(target, conn, C.REDIR))
plz add a new type instead of `C.REDIR`

2020-11-06 10:05 UTC, Dreamacro commented
本地测试过了么？ipv4 以及 ipv6

2020-11-09 01:51 UTC, ekenchan commented on proxy/redir/tproxy.go
> +	tunnel.Add(inbound.NewSocket(target, conn, C.REDIR))
add new type 'TPROXY'

2020-11-09 01:51 UTC, ekenchan commented on proxy/redir/tproxy.go
> +	rl := &TProxyListener{Listener: l,
done

2020-11-09 01:52 UTC, ekenchan commented
> 
> 
> 本地测试过了么？ipv4 以及 ipv6

无论是TCP还是UDP，ipv4和ipv6都是正常的

2020-11-09 02:39 UTC, Dreamacro commented
看起来新增的文件文本换行是 CRLF，可以通过 `go fmt ./...` 统一换成 LF

2020-11-09 02:42 UTC, ekenchan commented
> 
> 
> 看起来新增的文件文本换行是 CRLF，可以通过 `go fmt ./...` 统一换成 LF



> 
> 
> 看起来新增的文件文本换行是 CRLF，可以通过 `go fmt ./...` 统一换成 LF

got it

2020-11-09 02:46 UTC, merged

2020-11-09 02:46 UTC, Dreamacro commented
感谢耐心修改和贡献，请问介意这个 pr 被 cherry pick 到 premium 里么

2020-11-09 02:47 UTC, ekenchan commented
> 
> 
> 感谢耐心修改和贡献，请问介意这个 pr 被 cherry pick 到 premium 里么

可以，没问题

2020-11-22 16:37 UTC, junknet commented
有好心人贴一下配置文件吗 iptables 和 路由表的命令啥的

2020-11-24 13:48 UTC, isweibin commented
> 有好心人贴一下配置文件吗 iptables 和 路由表的命令啥的

您好，我在一台载有 Armbian（Debian）的 N1 盒子上运行 Clash 作为局域网中的网关服务器和 DNS 服务器，非常惭愧地是我在计算机网络相关方面仍然是一个小白，通过在网络上搜索相关文章我对我的配置文件做了如下更改：
```
# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
tproxy-port: 7893
```
并且使用了如下的 iptables 和路由规则：
```
# ROUTE RULES
ip rule add fwmark 1 table 100
ip route add local 0.0.0.0/0 dev lo table 100

# CREATE TABLE
iptables -t mangle -N clash

# RETURN LOCAL AND LANS
iptables -t mangle -A clash -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A clash -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A clash -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A clash -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A clash -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A clash -d 240.0.0.0/4 -j RETURN

# FORWARD ALL
iptables -t mangle -A clash -p udp -j TPROXY --on-port 7893 --tproxy-mark 1
iptables -t mangle -A clash -p tcp -j TPROXY --on-port 7893 --tproxy-mark 1

# REDIRECT
iptables -t mangle -A PREROUTING -j clash
```
目前正在使用中，看起来一切正常，如果有什么错误希望各位指正。

2020-11-25 01:03 UTC, maskedeken commented
> 
> 
> > 有好心人贴一下配置文件吗 iptables 和 路由表的命令啥的
> 
> 您好，我在一台载有 Armbian（Debian）的 N1 盒子上运行 Clash 作为局域网中的网关服务器和 DNS 服务器，非常惭愧地是我在计算机网络相关方面仍然是一个小白，通过在网络上搜索相关文章我对我的配置文件做了如下更改：
> 
> ```
> # Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
> # redir-port: 7892
> 
> # Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
> tproxy-port: 7893
> ```
> 
> 并且使用了如下的 iptables 和路由规则：
> 
> ```
> # ROUTE RULES
> ip rule add fwmark 1 table 100
> ip route add local 0.0.0.0/0 dev lo table 100
> 
> # CREATE TABLE
> iptables -t mangle -N clash
> 
> # RETURN LOCAL AND LANS
> iptables -t mangle -A clash -d 0.0.0.0/8 -j RETURN
> iptables -t mangle -A clash -d 10.0.0.0/8 -j RETURN
> iptables -t mangle -A clash -d 127.0.0.0/8 -j RETURN
> iptables -t mangle -A clash -d 169.254.0.0/16 -j RETURN
> iptables -t mangle -A clash -d 172.16.0.0/12 -j RETURN
> iptables -t mangle -A clash -d 192.168.0.0/16 -j RETURN
> iptables -t mangle -A clash -d 224.0.0.0/4 -j RETURN
> iptables -t mangle -A clash -d 240.0.0.0/4 -j RETURN
> 
> # FORWARD ALL
> iptables -t mangle -A clash -p udp -j TPROXY --on-port 7893 --tproxy-mark 1
> iptables -t mangle -A clash -p tcp -j TPROXY --on-port 7893 --tproxy-mark 1
> 
> # REDIRECT
> iptables -t mangle -A PREROUTING -j clash
> ```
> 
> 目前正在使用中，看起来一切正常，如果有什么错误希望各位指正。

还可以在OUTPUT中加入MARK --set-mark 1，让本机出去的流量也用clash代理

2020-11-29 08:19 UTC, junknet commented
> > > 有好心人贴一下配置文件吗 iptables 和 路由表的命令啥的
> > 
> > 
> > 您好，我在一台载有 Armbian（Debian）的 N1 盒子上运行 Clash 作为局域网中的网关服务器和 DNS 服务器，非常惭愧地是我在计算机网络相关方面仍然是一个小白，通过在网络上搜索相关文章我对我的配置文件做了如下更改：
> > ```
> > # Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
> > # redir-port: 7892
> > 
> > # Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
> > tproxy-port: 7893
> > ```
> > 
> > 
> > 并且使用了如下的 iptables 和路由规则：
> > ```
> > # ROUTE RULES
> > ip rule add fwmark 1 table 100
> > ip route add local 0.0.0.0/0 dev lo table 100
> > 
> > # CREATE TABLE
> > iptables -t mangle -N clash
> > 
> > # RETURN LOCAL AND LANS
> > iptables -t mangle -A clash -d 0.0.0.0/8 -j RETURN
> > iptables -t mangle -A clash -d 10.0.0.0/8 -j RETURN
> > iptables -t mangle -A clash -d 127.0.0.0/8 -j RETURN
> > iptables -t mangle -A clash -d 169.254.0.0/16 -j RETURN
> > iptables -t mangle -A clash -d 172.16.0.0/12 -j RETURN
> > iptables -t mangle -A clash -d 192.168.0.0/16 -j RETURN
> > iptables -t mangle -A clash -d 224.0.0.0/4 -j RETURN
> > iptables -t mangle -A clash -d 240.0.0.0/4 -j RETURN
> > 
> > # FORWARD ALL
> > iptables -t mangle -A clash -p udp -j TPROXY --on-port 7893 --tproxy-mark 1
> > iptables -t mangle -A clash -p tcp -j TPROXY --on-port 7893 --tproxy-mark 1
> > 
> > # REDIRECT
> > iptables -t mangle -A PREROUTING -j clash
> > ```
> > 
> > 
> > 目前正在使用中，看起来一切正常，如果有什么错误希望各位指正。
> 
> 还可以在OUTPUT中加入MARK --set-mark 1，让本机出去的流量也用clash代理

尴尬了，我这样代理本机流量 然后流量回环了

2020-11-29 11:19 UTC, wogong commented
> > 还可以在OUTPUT中加入MARK --set-mark 1，让本机出去的流量也用clash代理
> 
> 尴尬了，我这样代理本机流量 然后流量回环了
> 个人看了一下 v2ray 的解决tproxy代理本机流量回环的方案，
> 代理软件自身发出的流量使用SetSocketOption(貌似是这个函数来着) SO_MARK 标记为 0xFF ，然后利用路由表直接发送出去

同，搜索了一些看到了类似的，v2ray 的教程 （https://toutyrater.github.io/app/tproxy.html）貌似也是这么做的，不过还没尝试。您尝试成功了可以分享一下？

2020-11-30 01:05 UTC, maskedeken commented
> 
> 
> > > > 有好心人贴一下配置文件吗 iptables 和 路由表的命令啥的
> > > 
> > > 
> > > 您好，我在一台载有 Armbian（Debian）的 N1 盒子上运行 Clash 作为局域网中的网关服务器和 DNS 服务器，非常惭愧地是我在计算机网络相关方面仍然是一个小白，通过在网络上搜索相关文章我对我的配置文件做了如下更改：
> > > ```
> > > # Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
> > > # redir-port: 7892
> > > 
> > > # Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
> > > tproxy-port: 7893
> > > ```
> > > 
> > > 
> > > 并且使用了如下的 iptables 和路由规则：
> > > ```
> > > # ROUTE RULES
> > > ip rule add fwmark 1 table 100
> > > ip route add local 0.0.0.0/0 dev lo table 100
> > > 
> > > # CREATE TABLE
> > > iptables -t mangle -N clash
> > > 
> > > # RETURN LOCAL AND LANS
> > > iptables -t mangle -A clash -d 0.0.0.0/8 -j RETURN
> > > iptables -t mangle -A clash -d 10.0.0.0/8 -j RETURN
> > > iptables -t mangle -A clash -d 127.0.0.0/8 -j RETURN
> > > iptables -t mangle -A clash -d 169.254.0.0/16 -j RETURN
> > > iptables -t mangle -A clash -d 172.16.0.0/12 -j RETURN
> > > iptables -t mangle -A clash -d 192.168.0.0/16 -j RETURN
> > > iptables -t mangle -A clash -d 224.0.0.0/4 -j RETURN
> > > iptables -t mangle -A clash -d 240.0.0.0/4 -j RETURN
> > > 
> > > # FORWARD ALL
> > > iptables -t mangle -A clash -p udp -j TPROXY --on-port 7893 --tproxy-mark 1
> > > iptables -t mangle -A clash -p tcp -j TPROXY --on-port 7893 --tproxy-mark 1
> > > 
> > > # REDIRECT
> > > iptables -t mangle -A PREROUTING -j clash
> > > ```
> > > 
> > > 
> > > 目前正在使用中，看起来一切正常，如果有什么错误希望各位指正。
> > 
> > 
> > 还可以在OUTPUT中加入MARK --set-mark 1，让本机出去的流量也用clash代理
> 
> 尴尬了，我这样代理本机流量 然后流量回环了
> 个人看了一下 v2ray 的解决tproxy代理本机流量回环的方案，
> 代理软件自身发出的流量使用SetSocketOption(貌似是这个函数来着) SO_MARK 标记为 0xFF ，然后利用路由表直接发送出去

可以参考OpenClash的做法，用一个单独的用户启动clash，然后配置iptables规则，让这个用户出去的流量都走直通

2020-11-30 06:59 UTC, junknet commented
> > > > > 有好心人贴一下配置文件吗 iptables 和 路由表的命令啥的
> > > > 
> > > > 
> > > > 您好，我在一台载有 Armbian（Debian）的 N1 盒子上运行 Clash 作为局域网中的网关服务器和 DNS 服务器，非常惭愧地是我在计算机网络相关方面仍然是一个小白，通过在网络上搜索相关文章我对我的配置文件做了如下更改：
> > > > ```
> > > > # Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
> > > > # redir-port: 7892
> > > > 
> > > > # Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
> > > > tproxy-port: 7893
> > > > ```
> > > > 
> > > > 
> > > > 并且使用了如下的 iptables 和路由规则：
> > > > ```
> > > > # ROUTE RULES
> > > > ip rule add fwmark 1 table 100
> > > > ip route add local 0.0.0.0/0 dev lo table 100
> > > > 
> > > > # CREATE TABLE
> > > > iptables -t mangle -N clash
> > > > 
> > > > # RETURN LOCAL AND LANS
> > > > iptables -t mangle -A clash -d 0.0.0.0/8 -j RETURN
> > > > iptables -t mangle -A clash -d 10.0.0.0/8 -j RETURN
> > > > iptables -t mangle -A clash -d 127.0.0.0/8 -j RETURN
> > > > iptables -t mangle -A clash -d 169.254.0.0/16 -j RETURN
> > > > iptables -t mangle -A clash -d 172.16.0.0/12 -j RETURN
> > > > iptables -t mangle -A clash -d 192.168.0.0/16 -j RETURN
> > > > iptables -t mangle -A clash -d 224.0.0.0/4 -j RETURN
> > > > iptables -t mangle -A clash -d 240.0.0.0/4 -j RETURN
> > > > 
> > > > # FORWARD ALL
> > > > iptables -t mangle -A clash -p udp -j TPROXY --on-port 7893 --tproxy-mark 1
> > > > iptables -t mangle -A clash -p tcp -j TPROXY --on-port 7893 --tproxy-mark 1
> > > > 
> > > > # REDIRECT
> > > > iptables -t mangle -A PREROUTING -j clash
> > > > ```
> > > > 
> > > > 
> > > > 目前正在使用中，看起来一切正常，如果有什么错误希望各位指正。
> > > 
> > > 
> > > 还可以在OUTPUT中加入MARK --set-mark 1，让本机出去的流量也用clash代理
> > 
> > 
> > 尴尬了，我这样代理本机流量 然后流量回环了
> > 个人看了一下 v2ray 的解决tproxy代理本机流量回环的方案，
> > 代理软件自身发出的流量使用SetSocketOption(貌似是这个函数来着) SO_MARK 标记为 0xFF ，然后利用路由表直接发送出去
> 
> 可以参考OpenClash的做法，用一个单独的用户启动clash，然后配置iptables规则，让这个用户出去的流量都走直通

这方法吧，systemd 里面用user 区分也可，但是我个人吧，经常重装系统，建立clash用户 ，开机头像就有两个，

2020-12-01 11:12 UTC, junknet commented
> > > 还可以在OUTPUT中加入MARK --set-mark 1，让本机出去的流量也用clash代理
> > 
> > 
> > 尴尬了，我这样代理本机流量 然后流量回环了
> > 个人看了一下 v2ray 的解决tproxy代理本机流量回环的方案，
> > 代理软件自身发出的流量使用SetSocketOption(貌似是这个函数来着) SO_MARK 标记为 0xFF ，然后利用路由表直接发送出去
> 
> 同回环。搜索了一些看到了类似的教程，v2ray 的 [教程](https://toutyrater.github.io/app/tproxy.html) 也是这么做的，不过还没尝试。您尝试成功了可以分享一下？

这事还搞成了，改了组件的拨号器..go语言我刚学不久，不是很熟...
文件路径: component/dialer/dialer.go
这个大概是clash tcp发射出去流量使用的拨号器吧 ,红色的是我添加的
![tcp](https://user-images.githubusercontent.com/55597646/100733146-b40bff80-3408-11eb-86cf-51c72dfbb394.png)
这应该是udp的发射流量
![udp](https://user-images.githubusercontent.com/55597646/100733280-ea497f00-3408-11eb-8705-8f7c0313ae18.png)
下面配合 nftables的规则

![qwe](https://user-images.githubusercontent.com/55597646/100733340-fd5c4f00-3408-11eb-802a-94dcdd3d59f1.png)

嗯 就这样吧，也不提交请求了(作者坚持 使用用户UID区分开clash的流量) ... 我个人是不想建立新用户，开机两个头像看着烦

2020-12-02 01:01 UTC, maskedeken commented
> 
> 
> > > > 还可以在OUTPUT中加入MARK --set-mark 1，让本机出去的流量也用clash代理
> > > 
> > > 
> > > 尴尬了，我这样代理本机流量 然后流量回环了
> > > 个人看了一下 v2ray 的解决tproxy代理本机流量回环的方案，
> > > 代理软件自身发出的流量使用SetSocketOption(貌似是这个函数来着) SO_MARK 标记为 0xFF ，然后利用路由表直接发送出去
> > 
> > 
> > 同回环。搜索了一些看到了类似的教程，v2ray 的 [教程](https://toutyrater.github.io/app/tproxy.html) 也是这么做的，不过还没尝试。您尝试成功了可以分享一下？
> 
> 这事还搞成了，改了组件的拨号器..go语言我刚学不久，不是很熟...
> 文件路径: component/dialer/dialer.go
> 这个大概是clash tcp发射出去流量使用的拨号器吧 ,红色的是我添加的
> ![tcp](https://user-images.githubusercontent.com/55597646/100733146-b40bff80-3408-11eb-86cf-51c72dfbb394.png)
> 这应该是udp的发射流量
> ![udp](https://user-images.githubusercontent.com/55597646/100733280-ea497f00-3408-11eb-8705-8f7c0313ae18.png)
> 下面配合 nftables的规则
> 
> ![qwe](https://user-images.githubusercontent.com/55597646/100733340-fd5c4f00-3408-11eb-802a-94dcdd3d59f1.png)
> 
> 嗯 就这样吧，也不提交请求了(作者坚持 使用用户UID区分开clash的流量) ... 我个人是不想建立新用户，开机两个头像看着烦

其实可以增加nologin的用户，就不会出现登录头像了

2020-12-02 04:14 UTC, junknet commented
> > > > > 还可以在OUTPUT中加入MARK --set-mark 1，让本机出去的流量也用clash代理
> > > > 
> > > > 
> > > > 尴尬了，我这样代理本机流量 然后流量回环了
> > > > 个人看了一下 v2ray 的解决tproxy代理本机流量回环的方案，
> > > > 代理软件自身发出的流量使用SetSocketOption(貌似是这个函数来着) SO_MARK 标记为 0xFF ，然后利用路由表直接发送出去
> > > 
> > > 
> > > 同回环。搜索了一些看到了类似的教程，v2ray 的 [教程](https://toutyrater.github.io/app/tproxy.html) 也是这么做的，不过还没尝试。您尝试成功了可以分享一下？
> > 
> > 
> > 这事还搞成了，改了组件的拨号器..go语言我刚学不久，不是很熟...
> > 文件路径: component/dialer/dialer.go
> > 这个大概是clash tcp发射出去流量使用的拨号器吧 ,红色的是我添加的
> > ![tcp](https://user-images.githubusercontent.com/55597646/100733146-b40bff80-3408-11eb-86cf-51c72dfbb394.png)
> > 这应该是udp的发射流量
> > ![udp](https://user-images.githubusercontent.com/55597646/100733280-ea497f00-3408-11eb-8705-8f7c0313ae18.png)
> > 下面配合 nftables的规则
> > ![qwe](https://user-images.githubusercontent.com/55597646/100733340-fd5c4f00-3408-11eb-802a-94dcdd3d59f1.png)
> > 嗯 就这样吧，也不提交请求了(作者坚持 使用用户UID区分开clash的流量) ... 我个人是不想建立新用户，开机两个头像看着烦
> 
> 其实可以增加nologin的用户，就不会出现登录头像了

啊这....感谢大佬，学到了；
我直接在clash.service 用root组启动了...  nftables : meta skuid root return

2020-12-07 08:18 UTC, Student414 commented
> > 有好心人贴一下配置文件吗 iptables 和 路由表的命令啥的
> 
> 您好，我在一台载有 Armbian（Debian）的 N1 盒子上运行 Clash 作为局域网中的网关服务器和 DNS 服务器，非常惭愧地是我在计算机网络相关方面仍然是一个小白，通过在网络上搜索相关文章我对我的配置文件做了如下更改：
> 
> ```
> # Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
> # redir-port: 7892
> 
> # Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
> tproxy-port: 7893
> ```
> 
> 并且使用了如下的 iptables 和路由规则：
> 
> ```
> # ROUTE RULES
> ip rule add fwmark 1 table 100
> ip route add local 0.0.0.0/0 dev lo table 100
> 
> # CREATE TABLE
> iptables -t mangle -N clash
> 
> # RETURN LOCAL AND LANS
> iptables -t mangle -A clash -d 0.0.0.0/8 -j RETURN
> iptables -t mangle -A clash -d 10.0.0.0/8 -j RETURN
> iptables -t mangle -A clash -d 127.0.0.0/8 -j RETURN
> iptables -t mangle -A clash -d 169.254.0.0/16 -j RETURN
> iptables -t mangle -A clash -d 172.16.0.0/12 -j RETURN
> iptables -t mangle -A clash -d 192.168.0.0/16 -j RETURN
> iptables -t mangle -A clash -d 224.0.0.0/4 -j RETURN
> iptables -t mangle -A clash -d 240.0.0.0/4 -j RETURN
> 
> # FORWARD ALL
> iptables -t mangle -A clash -p udp -j TPROXY --on-port 7893 --tproxy-mark 1
> iptables -t mangle -A clash -p tcp -j TPROXY --on-port 7893 --tproxy-mark 1
> 
> # REDIRECT
> iptables -t mangle -A PREROUTING -j clash
> ```
> 
> 目前正在使用中，看起来一切正常，如果有什么错误希望各位指正。

貌似不兼容Docker，在Container中直接无法访问任何外网，除非加`iptables -t mangle -A CLASH -s 172.17.0.0/16 -j RETURN`
但是这样的话，Docker里面的请求就不走Clash了，很烦。

2021-03-22 11:42 UTC, contrun commented
@Student414  https://github.com/springzfx/cgproxy/blob/aaa628a76b2911018fc93b2e3276c177e85e0861/readme.md#known-issues 这里说的方法可以解决 docker 容器不能使用透明代理的问题。

2021-03-22 12:42 UTC, Student414 commented
> @Student414 https://github.com/springzfx/cgproxy/blob/aaa628a76b2911018fc93b2e3276c177e85e0861/readme.md#known-issues 这里说的方法可以解决 docker 容器不能使用透明代理的问题。

此问题已解决，iptables规则的问题，没捕获output链数据，哈哈~

2021-08-16 02:07 UTC, tiandongxv commented
> > @Student414 https://github.com/springzfx/cgproxy/blob/aaa628a76b2911018fc93b2e3276c177e85e0861/readme.md#known-issues 这里说的方法可以解决 docker 容器不能使用透明代理的问题。
> 
> 此问题已解决，iptables规则的问题，没捕获output链数据，哈哈~

您好，可否分享一下你的iptables设置和样本config.yaml，麻烦您了！

2021-08-16 02:35 UTC, Student414 commented
> > > @Student414 https://github.com/springzfx/cgproxy/blob/aaa628a76b2911018fc93b2e3276c177e85e0861/readme.md#known-issues 这里说的方法可以解决 docker 容器不能使用透明代理的问题。
> > 
> > 
> > 此问题已解决，iptables规则(包含docker)的问题，没捕获output链数据，哈哈~
> 
> 您好，可否分享一下你的iptables设置和样本config.yaml，麻烦您了！

https://gitee.com/wangfuying_admin/linux-transparent-proxy-script
如果有问题，帮忙改改:）

Docker据小伙反馈完美支持，但是我这边需要在ufw-not-local链中加一条规则才可以，如果不使用ufw，请忽略。

2021-08-18 02:01 UTC, wwqgtxx commented
> > > > @Student414 https://github.com/springzfx/cgproxy/blob/aaa628a76b2911018fc93b2e3276c177e85e0861/readme.md#known-issues 这里说的方法可以解决 docker 容器不能使用透明代理的问题。
> > > 
> > > 
> > > 此问题已解决，iptables规则(包含docker)的问题，没捕获output链数据，哈哈~
> > 
> > 
> > 您好，可否分享一下你的iptables设置和样本config.yaml，麻烦您了！
> 
> 透明代理：
> https://gitee.com/wangfuying_admin/linux-transparent-proxy-script
> 如果有问题，帮忙改改:）
> 
> Clash配置：（很普通的配置）
> 
> ```
> # HTTP 代理端口
> port: 7890
> 
> # SOCKS5 代理端口
> socks-port: 7891
> 
> # Linux 和 macOS 的 redir 代理端口
> redir-port: 7892
> 
> # Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
> tproxy-port: 7893
> 
> # 允许局域网的连接
> allow-lan: true
> 
> # 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
> mode: rule
> 
> # 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
> # 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
> log-level: error
> # Clash 的 RESTful API
> external-controller: "0.0.0.0:9090"
> 
> # RESTful API 的口令
> secret: ""
> 
> # 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
> # 参数应填写配置目录的相对路径或绝对路径。
> external-ui: ui
> 
> ipv6: true
> 
> dns:
>   enable: true
>   ipv6: true
>   listen: 0.0.0.0:1053
>   enhanced-mode: redir-host # or fake-ip
>   nameserver:
>     #- 119.29.29.29 # 腾讯DNSPod
>     - 180.76.76.76 # 百度
>     - 223.5.5.5 # 阿里
>   fallback:
>     - tls://8.8.8.8:853 # Google
>     - tls://1.1.1.1 # cloudflare
>     - https://1.1.1.1/dns-query # cloudflare
>   fallback-filter:
>     geoip: true
>     ipcidr:
>       - 240.0.0.0/4
> ```
> 
> Docker据小伙伴反馈完美支持，但是我这边在用ufw，需要在ufw-not-local链中加一条规则才可以，如果不使用ufw，请忽略。

在脚本中还是把
```bash
sysctl -w net.bridge.bridge-nf-call-iptables=0 || true
sysctl -w net.bridge.bridge-nf-call-ip6tables=0 || true
sysctl -w net.bridge.bridge-nf-call-arptables=0 || true
```
加上呗，既然一键脚本就做的彻底点吧

2021-12-24 06:06 UTC, fuwu1245 commented
> > > > @Student414 https://github.com/springzfx/cgproxy/blob/aaa628a76b2911018fc93b2e3276c177e85e0861/readme.md#known-issues 这里说的方法可以解决 docker 容器不能使用透明代理的问题。
> > > 
> > > 
> > > 此问题已解决，iptables规则(包含docker)的问题，没捕获output链数据，哈哈~
> > 
> > 
> > 您好，可否分享一下你的iptables设置和样本config.yaml，麻烦您了！
> 
> 透明代理： https://gitee.com/wangfuying_admin/linux-transparent-proxy-script 如果有问题，帮忙改改:）
> 
> Clash配置：（很普通的配置）
> 
> ```
> # HTTP 代理端口
> port: 7890
> 
> # SOCKS5 代理端口
> socks-port: 7891
> 
> # Linux 和 macOS 的 redir 代理端口
> redir-port: 7892
> 
> # Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
> tproxy-port: 7893
> 
> # 允许局域网的连接
> allow-lan: true
> 
> # 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
> mode: rule
> 
> # 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
> # 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
> log-level: error
> # Clash 的 RESTful API
> external-controller: "0.0.0.0:9090"
> 
> # RESTful API 的口令
> secret: ""
> 
> # 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
> # 参数应填写配置目录的相对路径或绝对路径。
> external-ui: ui
> 
> ipv6: true
> 
> dns:
>   enable: true
>   ipv6: true
>   listen: 0.0.0.0:1053
>   enhanced-mode: redir-host # or fake-ip
>   nameserver:
>     #- 119.29.29.29 # 腾讯DNSPod
>     - 180.76.76.76 # 百度
>     - 223.5.5.5 # 阿里
>   fallback:
>     - tls://8.8.8.8:853 # Google
>     - tls://1.1.1.1 # cloudflare
>     - https://1.1.1.1/dns-query # cloudflare
>   fallback-filter:
>     geoip: true
>     ipcidr:
>       - 240.0.0.0/4
> ```
> 
> Docker据小伙伴反馈完美支持，但是我这边在用ufw，需要在ufw-not-local链中加一条规则才可以，如果不使用ufw，请忽略。
我在我的软路由上用了你这个iptables，AppStore打不开是为什么？

2022-07-14 20:21 UTC, Student414 commented
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

2022-07-14 20:24 UTC, escape0707 commented
> 我照抄之后,  curl google.com 没有返回信息.
> 
> 一定要 curl google.com -x socks5://xxxxxxxxxxx 才行.
> 
> 是不是dns没有设置正确?

如果担心是dns问题，发一下clash日志。

2023-07-01 05:49 UTC, etoyz commented
> > 
> > 
> > 其实可以增加nologin的用户，就不会出现登录头像了
> 
> 啊这....感谢大佬，学到了； 我直接在clash.service 用root组启动了... nftables : meta skuid root return

这样做好像有个缺点，那就是root用户没办法走代理了。。。
其实netfilter本身支持pid和cmd匹配，按理来说应该这样做：
直接匹配到clash进程，然后让clash走直连，可惜pid和cmd匹配的功能在多核心架构下broken了。[>>>](https://www.frozentux.net/iptables-tutorial/iptables-tutorial.html#OWNERMATCH)
所以最好的方法还是新建一个专门运行clash的用户

_The pid, sid and command matching is broken in SMP kernels since they use different process lists for each processor. It might be fixed in the future however_

2023-07-01 05:49 UTC, Student414 commented
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。