[bugfix]: close http body.
Dreamacro/clash pull request #1154
Opened 2020-12-28 04:53 UTC by xiekeyi98

Close any http body  that are not turned off.

2020-12-28 05:22 UTC, Dreamacro requested changes

2020-12-28 05:22 UTC, Dreamacro commented on component/vmess/h2.go
> +	defer res.Body.Close()
https://github.com/Dreamacro/clash/blob/bbe0fe3ae625247c08e5c722d3d38773dbf18682/component/vmess/h2.go#L71

it Read from res.Body after `establishConn`

2020-12-28 05:22 UTC, Dreamacro commented on component/vmess/websocket.go
>  		}
It is also possible `resp ! = nil`

2020-12-28 05:32 UTC, xiekeyi98 commented
Thanks for your guidance, I will think more carefully and submit another relevant pr request.

2020-12-28 05:34 UTC, Dreamacro commented
@xiekeyi98 You can change it on the basis of this pr, just `push --force`

2020-12-28 06:16 UTC, xiekeyi98 commented
> @xiekeyi98 You can change it on the basis of this pr, just `push --force`

appreciate it!
I was just not sure what I do is necessary, I don't think I've thought about it very much.

PTAL~

2020-12-28 06:31 UTC, Dreamacro requested changes

2020-12-28 06:31 UTC, Dreamacro commented on tunnel/connection.go
> +		defer resp.Body.Close()
The Response Body is closed after Response.Write.

https://golang.org/pkg/net/http/#Response.Write

2020-12-28 15:56 UTC, Dreamacro commented on component/vmess/h2.go
> +	// it will be close at : (hc *h2Conn) establishConn()
To be precise, it will close here at https://github.com/Dreamacro/clash/blob/163400143161443494d9cc8936b14d73cee5365e/component/vmess/h2.go#L86

2020-12-28 15:59 UTC, xiekeyi98 commented on component/vmess/h2.go
> +	// it will be close at : (hc *h2Conn) establishConn()
多谢，老哥你真是回复的又快……又 24 小时在线啊。。。

2020-12-28 16:01 UTC, Dreamacro commented on component/vmess/h2.go
> +	// it will be close at : (hc *h2Conn) establishConn()
or you can write

```go
if hc.res != nil {
    hc.res.Body.Close()
}
```

2020-12-28 16:03 UTC, xiekeyi98 commented on component/vmess/h2.go
> +	// it will be close at : (hc *h2Conn) establishConn()
By my guess, close is not guaranteed to be idempotent, depending on the specific implementation.

2020-12-28 16:15 UTC, Dreamacro commented on component/vmess/h2.go
> +	// it will be close at : (hc *h2Conn) establishConn()
确实我不太清楚 ClientConn.Shutdown 和 Conn.Close 是否会让 Body 正常关闭。

2020-12-29 02:27 UTC, xiekeyi98 commented on component/vmess/h2.go
> +	// it will be close at : (hc *h2Conn) establishConn()
我是觉得这样写有点奇怪，而且会被这样的检测工具(https://github.com/timakin/bodyclose)报错，所以我加了注释。不过要是改也感觉没什么好想法……

2020-12-29 02:56 UTC, Dreamacro commented on component/vmess/h2.go
> +	// it will be close at : (hc *h2Conn) establishConn()
这些工具都是有局限性的，包括使用 Response.Write 会自动 close Body 这个情况其实要完全考虑到很难。所以目前我只用了一个静态检查的东西 honnef.co/go/tools/cmd/staticcheck

像这里 Conn.Close 到底会不会使 Body 这个 resource 释放（直觉上我认为是会的），这个我得详细看看源码才能知道。

2020-12-29 03:28 UTC, merged

2020-12-29 03:32 UTC, xiekeyi98 commented on component/vmess/h2.go
> +	// it will be close at : (hc *h2Conn) establishConn()
这类工具确实误报都比较多，对于一个 clash 这样网络工具来说，又很难完全做到。