Refactor ssr
Dreamacro/clash pull request #1189
Opened 2021-01-19 18:14 UTC by goomadao

2021-01-26 16:28 UTC, goomadao commented
https://github.com/Dreamacro/clash/pull/1189/commits/9c01a53f91a5598263c67f9570346badf79d7365 这个问题很奇怪

在[tcprelay.py](https://github.com/shadowsocksr-backup/shadowsocksr/blob/manyuser/shadowsocks/tcprelay.py#L1208-L1209)中是可以正常执行`_update_users`的
```python3
if common.to_str(config['protocol']) in obfs.mu_protocol():
  self._update_users(None, None)
```

但是在[udprelay.py](https://github.com/shadowsocksr-backup/shadowsocksr/blob/manyuser/shadowsocks/udprelay.py#L165-L166)中，使用的却是`to_bytes`，所以server在udpRelay里不能正常加载protocol-param中设定的user，在udpRelay里users列表是空的
```python3
if common.to_bytes(config['protocol']) in obfs.mu_protocol():
  self._update_users(None, None)
```

而无论是在[auth.py](https://github.com/shadowsocksr-backup/shadowsocksr/blob/manyuser/shadowsocks/obfsplugin/auth.py#L546-L554)还是在[auth_chain.py](https://github.com/shadowsocksr-backup/shadowsocksr/blob/manyuser/shadowsocks/obfsplugin/auth_chain.py#L563-L573)的client中，都又将`split(b':')`错写成了`split(':')`，所以python版的server和client恰好就能协同工作
```python3
items = to_bytes(self.server_info.protocol_param).split(':')
```

我也说不清这是bug还是feature，可能得看看各个ssr后端是怎么实现的？

2021-01-27 02:42 UTC, Dreamacro commented
已最多人使用的开源 server 版本为准，不管它是不是一个 bug 或者 feature。由于 ssr 已经年久失修，所以这些都没有办法去解决

2021-01-27 03:03 UTC, wwqgtxx commented
实测在 https://github.com/Dreamacro/clash/commit/9c01a53f91a5598263c67f9570346badf79d7365 之后，使用`auth_aes128_sha1+plain`的机场无法正常进行UDP通讯了，根据我之前自己的测试，上一个版本的逻辑才是对的
https://github.com/wwqgtxx/gossr/commit/5893452bb0d87fb66a6ad04402bd7c9ddfdddde6#diff-a2627abac1b1674f8514d9610a18fe6b61bd4a1f11c4da9e71a62b69c2946c39R284
上面是我自己以前的实现，在大部分机场环境下工作正常

2021-01-27 03:50 UTC, goomadao commented
我用的机场没有使用auth_aes128和auth_chain，所以没办法验证。

另外昨天晚上我也发现了，https://github.com/shadowsocksrr/shadowsocksr/commit/08b88026e884eac456b0d7dee1d5dbcbf30cebe3#diff-b01f7fc4b3e3fe38e85b9c02c563acd4e44dfdf70a150c897b65f4c264ba3d73L165-R165 修复了这个问题，目测这个server用的人可能会多一些，稍后我再把 https://github.com/Dreamacro/clash/commit/9c01a53f91a5598263c67f9570346badf79d7365 revert掉

2021-01-27 04:07 UTC, wwqgtxx commented
其实主流的ssr后端可以参考一下这个
https://github.com/Anankke/shadowsocks-mod
毕竟这是现在用的最多的SSPanel-Uim面板的配套后端，其他的后端虽然大部分没开源，但是应该是和这个后端对外表现是一致的

2021-01-27 04:11 UTC, goomadao commented
@wwqgtxx 好的，感谢，我对这方面了解确实不太多，稍后我用这个后端测试一下

2021-01-27 12:06 UTC, simonsmh commented
测试了 commit `7b5c460`， revert 掉了`9c01a53`，发现内存泄漏很严重，10分钟就能爆2G而被OOM，同时提示 too many open files
protocol 为 auth_aes128_md5
obfs 为 http_simple
udp 开启

<details><summary>Dmesg Log</summary>

```
[74459.457980] clash invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
[74459.459113] CPU: 1 PID: 26338 Comm: clash Not tainted 5.4.92 #0
[74459.459643] Hardware name: FriendlyElec NanoPi R2S (DT)
[74459.460102] Call trace:
[74459.460332]  dump_backtrace+0x0/0x108
[74459.460657]  show_stack+0x14/0x20
[74459.460954]  dump_stack+0xc0/0x120
[74459.461261]  dump_header+0x40/0x1f4
[74459.461574]  oom_kill_process+0x1cc/0x1d0
[74459.461927]  out_of_memory+0xc8/0x2c8
[74459.462255]  __alloc_pages_slowpath+0x890/0x9c0
[74459.462653]  __alloc_pages_nodemask+0x1fc/0x280
[74459.463055]  pagecache_get_page+0x160/0x318
[74459.463425]  filemap_fault+0x474/0x908
[74459.463762]  ext4_filemap_fault+0x30/0x560
[74459.464125]  __do_fault+0x38/0x100
[74459.464425]  __handle_mm_fault+0x920/0xc28
[74459.464785]  handle_mm_fault+0xdc/0x1a8
[74459.465124]  do_page_fault+0x11c/0x438
[74459.465456]  do_translation_fault+0x64/0x70
[74459.465827]  do_mem_abort+0x3c/0x98
[74459.466135]  do_el0_ia_bp_hardening+0x5c/0xa8
[74459.466519]  el0_ia+0x18/0x1c
[74459.466848] Mem-Info:
[74459.467073] active_anon:234457 inactive_anon:675 isolated_anon:0
[74459.467073]  active_file:39 inactive_file:168 isolated_file:0
[74459.467073]  unevictable:0 dirty:0 writeback:0 unstable:0
[74459.467073]  slab_reclaimable:1937 slab_unreclaimable:5732
[74459.467073]  mapped:402 shmem:806 pagetables:660 bounce:0
[74459.467073]  free:4778 free_pcp:615 free_cma:0
[74459.469901] Node 0 active_anon:937828kB inactive_anon:2700kB active_file:156kB inactive_file:792kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:1668kB dirty:0kB writeback:0kB shmem:3224kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 428032kB writeback_tmp:0kB unstable:0kB all_unreclaimable? yes
[74459.472429] DMA32 free:18784kB min:16384kB low:20480kB high:24576kB active_anon:937828kB inactive_anon:2700kB active_file:124kB inactive_file:1568kB unevictable:0kB writepending:0kB present:1046528kB managed:1014632kB mlocked:0kB kernel_stack:1904kB pagetables:2640kB bounce:0kB free_pcp:2376kB local_pcp:868kB free_cma:0kB
[74459.474943] lowmem_reserve[]: 0 0 0
[74459.475267] DMA32: 298*4kB (UMEH) 672*8kB (UMEH) 339*16kB (UMEH) 110*32kB (UME) 36*64kB (UME) 7*128kB (UM) 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 18712kB
[74459.476538] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
[74459.477299] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=32768kB
[74459.478043] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
[74459.479013] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=64kB
[74459.479740] 1324 total pagecache pages
[74459.480072] 0 pages in swap cache
[74459.480365] Swap cache stats: add 0, delete 0, find 0/0
[74459.480821] Free swap  = 0kB
[74459.481074] Total swap = 0kB
[74459.481329] 261632 pages RAM
[74459.481582] 0 pages HighMem/MovableOnly
[74459.481919] 7974 pages reserved
[74459.482247] 2048 pages cma reserved
[74459.482561] Tasks state (memory values in pages):
[74459.482971] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[74459.483761] [    281]    81   281      307       33    40960        0             0 ubusd
[74459.484480] [    282]     0   282      204        9    32768        0             0 askfirst
[74459.485220] [    312]     0   312      236       11    36864        0             0 urngd
[74459.485937] [    694]   514   694      295       38    40960        0             0 logd
[74459.486699] [    746]     0   746      666      112    40960        0             0 rpcd
[74459.487413] [    943]     0   943      253       15    36864        0             0 dropbear
[74459.488152] [   1053]     0  1053      450       47    36864        0             0 netifd
[74459.488876] [   1110]     0  1110      357       34    45056        0             0 odhcpd
[74459.489603] [   1318]     0  1318      422       72    49152        0             0 uhttpd
[74459.490377] [   1408]     0  1408      406       29    40960        0             0 dbus-daemon
[74459.491151] [   1499] 65534  1499      539       14    36864        0             0 avahi-daemon
[74459.491921] [   1998]     0  1998     8758      843   106496        0             0 smbd
[74459.492631] [   1999]     0  1999     5502      321    81920        0             0 nmbd
[74459.493342] [   2057]     0  2057      303       16    32768        0             0 ntpd
[74459.494052] [   2152]     0  2152     8334      405    98304        0             0 smbd-notifyd
[74459.494849] [   2153]     0  2153     8332      403    94208        0             0 cleanupd
[74459.495594] [   2223]     0  2223      243       15    32768        0             0 odhcp6c
[74459.496350] [   2224]     0  2224      303        9    36864        0             0 udhcpc
[74459.497085] [   8287]     0  8287      259       15    45056        0             0 dropbear
[74459.497854] [   8288]     0  8288      305       16    40960        0             0 ash
[74459.498602] [  13294]     0 13294      259       19    45056        0             0 dropbear
[74459.499347] [  13295]     0 13295      305       15    45056        0             0 ash
[74459.500054] [  24939]     0 24939      425      137    36864        0             0 sh
[74459.500783] [  25736]     0 25736      303       12    32768        0             0 crond
[74459.501505] [  26333] 65534 26333   416360   232524  1990656        0             0 clash
[74459.502263] [  27127]     0 27127      478       14    36864        0             0 dnsmasq
[74459.503000] [  27129]     0 27129      320       29    36864        0             0 sh
[74459.503706] [  27130]     0 27130      303       13    32768        0             0 openclash_histo
[74459.504531] [  27139]     0 27139      268        8    32768        0             0 dhcpv6.script
[74459.505315] [  27140]     0 27140      258       17    45056        0             0 dropbear
[74459.506055] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=clash,pid=26333,uid=65534
[74459.507294] Out of memory: Killed process 26333 (clash) total-vm:1665440kB, anon-rss:930096kB, file-rss:0kB, shmem-rss:0kB, UID:65534 pgtables:1944kB oom_score_adj:0
[74459.676854] oom_reaper: reaped process 26333 (clash), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

</details>

2021-01-27 12:13 UTC, goomadao commented
> 测试了 commit `7b5c460`， revert 掉了`9c01a53`，发现内存泄漏很严重，10分钟就能爆2G而被OOM，同时提示 too many open files
> protocol 为 auth_aes128_md5
> obfs 为 http_simple
> udp 开启
> 
> Dmesg Log

感谢，正在排查

2021-01-30 06:49 UTC, goomadao commented
@simonsmh 我在本地用如下server config没有复现内存泄露的问题
<details>
<summary>server config</summary>

```json
{
  "server": "0.0.0.0",
  "server_ipv6": "::",
  "local_address": "127.0.0.1",
  "local_port": 1080,
  "server_port": 1025,
  "password": "123456m",
  "timeout": 300,
  "method": "rc4-md5",
  "protocol": "auth_aes128_md5",
  "protocol_param": "64#12345:bw,233:zhihuyaowan",
  "obfs": "http_simple",
  "obfs_param": "download.windowsupdate.com",
  "redirect": "",
  "dns_ipv6": false,
  "fast_open": false,
  "workers": 1
}
```
</details>

不过https://github.com/Dreamacro/clash/pull/1189/commits/a2ca82b2b06a0110bef0ee357d7ef4664d2df26a 修复了一个有可能会导致内存泄露的问题，可以麻烦你再试一下吗

2021-01-30 15:19 UTC, nameless3721 commented
> @simonsmh 我在本地用如下server config没有复现内存泄露的问题
> 
> server config
> 不过[a2ca82b](https://github.com/Dreamacro/clash/commit/a2ca82b2b06a0110bef0ee357d7ef4664d2df26a) 修复了一个有可能会导致内存泄露的问题，可以麻烦你再试一下吗

应该还有我这里测是linux armv8和amd64的内核 测速时候跑下行速度比较快的话内存会疯狂占用然后崩了

2021-01-30 15:20 UTC, goomadao commented
> > @simonsmh 我在本地用如下server config没有复现内存泄露的问题
> > server config
> > 不过[a2ca82b](https://github.com/Dreamacro/clash/commit/a2ca82b2b06a0110bef0ee357d7ef4664d2df26a) 修复了一个有可能会导致内存泄露的问题，可以麻烦你再试一下吗
> 
> 应该还有我这里测是linux armv8和amd64的内核 测速时候跑下行速度比较快的话内存会疯狂占用然后崩了

好的，我这里复现了，不过不是稳定复现，正在尝试解决

2021-01-30 15:31 UTC, nameless3721 commented
> > > @simonsmh 我在本地用如下server config没有复现内存泄露的问题
> > > server config
> > > 不过[a2ca82b](https://github.com/Dreamacro/clash/commit/a2ca82b2b06a0110bef0ee357d7ef4664d2df26a) 修复了一个有可能会导致内存泄露的问题，可以麻烦你再试一下吗
> > 
> > 
> > 应该还有我这里测是linux armv8和amd64的内核 测速时候跑下行速度比较快的话内存会疯狂占用然后崩了
> 
> 好的，我这里复现了，不过不是稳定复现，正在尝试解决

![image](https://user-images.githubusercontent.com/50364156/106360221-9ef51380-635a-11eb-83f5-c839a3339374.png)
这是tun内核的占用算是正常跑完
![image](https://user-images.githubusercontent.com/50364156/106360297-0c08a900-635b-11eb-88d8-3d0a57449ea0.png)
为了比较好崩我是设置成256内存的虚拟机基本都能复现他跑一下就占用快200内存然后Watchdog: Clash Core Problem, Restart 虽然是openclash 不过电脑是填clash的http代理应该用不到其他透明代理的脚本

2021-02-01 05:24 UTC, Kr328 commented
如果是连接数非常多的话 会不会和 https://github.com/Dreamacro/clash/pull/1209 有关

2021-02-01 14:03 UTC, goomadao commented
> 如果是连接数非常多的话 会不会和 #1209 有关

应该是我实现有问题，一般大流量连接（比如测速）比较容易触发

2021-02-02 05:43 UTC, Dreamacro commented on component/ssr/obfs/http_simple.go
> +		buf = append(buf, []byte("POST /")...)
对于频繁对 buffer 的长度进行扩充写的操作，使用 bytes.Buffer 比 []byte 要更方便和高效

2021-02-02 05:47 UTC, Dreamacro commented on component/ssr/obfs/http_simple.go
> +		buf = append(buf, []byte("POST /")...)
对 []byte 的操作心智负担会更加大，包括从 pool 里拿出来的 buffer, 需要保证不再被其他地方所引用，避免内存泄露或者不必要的被复写。

2021-02-02 05:48 UTC, goomadao commented on component/ssr/obfs/http_simple.go
> +		buf = append(buf, []byte("POST /")...)
这里的buf是外层`Write`函数通过`pool.Get`得到的，len为`0`cap为`pool.RelayBufferSize`

2021-02-02 05:49 UTC, Dreamacro commented on component/ssr/tools/binary.go
> +func AppendUint32LittleEndian(b []byte, v uint32) []byte {
这些 go 的 std 库都有 https://golang.org/pkg/encoding/binary/

2021-02-02 05:53 UTC, goomadao commented on component/ssr/obfs/http_simple.go
> +		buf = append(buf, []byte("POST /")...)
确实...内存泄露问题就出在buf上。 很难满足[这个条件](https://github.com/goomadao/clash/blob/refactor-ssr/component/ssr/protocol/auth_aes128_sha1.go#L140-L144)将buf正常Put掉。正在考虑其他的写法比如ssr使用自己的bytes.Buffer pool

2021-02-02 05:53 UTC, Dreamacro commented on component/ssr/tools/random.go
> +type XorShift128Plus struct {
这个伪随机数生成器有被用于校验么？如果没有的话是不是可以用 std 里的 crypto random 代替

2021-02-02 05:55 UTC, goomadao commented on component/ssr/tools/random.go
> +type XorShift128Plus struct {
有的，server端的随机数也是通过这个生成的，client和server必须要保持一致

2021-02-02 05:57 UTC, Dreamacro commented on component/ssr/obfs/http_simple.go
> +		buf = append(buf, []byte("POST /")...)
类似 trojan 里的 pool 就行了

2021-02-03 02:23 UTC, CoderTonyChan commented
https://github.com/Dreamacro/go-shadowsocks2/pull/2

能否把none也加上呢？

2021-02-08 10:17 UTC, goomadao commented
@Dreamacro https://github.com/Dreamacro/clash/pull/1189/commits/2ce664f3b7089ced733b2e16228416dfbb74f265 添加了dummy，不过我觉得在go-shadowsocks2里面把dummy放在streamCipher好一点，因为ssr就算是使用dummy加密也需要调用`core.Kdf`来计算Key，而且这样ssr就可以少一些类型判断。

2021-02-09 06:59 UTC, nameless3721 commented
试了最新的 9-g067a4ba auth_aes128_md5 和 tls1.2_ticket_auth 内存占用正常基本正常用了  然后还有个现存的clash核心都有的小问题有些服务商的后端ssr是 origin http_simple的然后通过 obfs来鉴权 格式是 123456-password.download.microsoft.com 的节点会用不了 普通ssr客户端是正常 也试过vps搭过一模一样参数但是做不了obfs鉴权在clash是通的 目前觉得是clash ssr的obfs发回去服务端数据可能不太一样？ 不过这类服务商一般ss和r的协议都提供所以影响不大

2021-02-09 07:19 UTC, goomadao commented
> 试了最新的 9-g067a4ba auth_aes128_md5 和 tls1.2_ticket_auth 内存占用正常基本正常用了 然后还有个现存的clash核心都有的小问题有些服务商的后端ssr是 origin http_simple的然后通过 obfs来鉴权 格式是 123456-password.download.microsoft.com 的节点会用不了 普通ssr客户端是正常 也试过vps搭过一模一样参数但是做不了obfs鉴权在clash是通的 目前觉得是clash ssr的obfs发回去服务端数据可能不太一样？ 不过这类服务商一般ss和r的协议都提供所以影响不大

可以发一下obfs-param吗，可能是bug，不过这种情况他们应该是魔改了后端，不一定能修

2021-02-09 08:08 UTC, nameless3721 commented
> > 试了最新的 9-g067a4ba auth_aes128_md5 和 tls1.2_ticket_auth 内存占用正常基本正常用了 然后还有个现存的clash核心都有的小问题有些服务商的后端ssr是 origin http_simple的然后通过 obfs来鉴权 格式是 123456-password.download.microsoft.com 的节点会用不了 普通ssr客户端是正常 也试过vps搭过一模一样参数但是做不了obfs鉴权在clash是通的 目前觉得是clash ssr的obfs发回去服务端数据可能不太一样？ 不过这类服务商一般ss和r的协议都提供所以影响不大
> 
> 可以发一下obfs-param吗，可能是bug，不过这种情况他们应该是魔改了后端，不一定能修

应该是魔改的后端才能obfs鉴权了 obfs-param: 23456-password.download.microsoft.com   是这样的前面是用户id然后-密码  密码只能英文数字 不能有特殊字符的 自己搭的后端无法强制用obfs的样子填啥都通

2021-02-09 12:15 UTC, Kr328 commented
顺便问一下这个 PR 完成了吗

obfs 部分改动非常大 用 Read/Write 替代了 Encode/Decode 
protocol 部分似乎还是 Encode/Decode 

是之后还有其他的未完成的部分吗

2021-02-09 13:18 UTC, goomadao commented on component/ssr/obfs/tls1.2_ticket_auth.go
> +		c.ticketBuf[u] = make([]byte, bufLen)
这里键是string，所以用了map。还是说为了提高性能应该用其他的类型？

2021-02-09 13:21 UTC, goomadao commented
> 顺便问一下这个 PR 完成了吗
> 
> obfs 部分改动非常大 用 Read/Write 替代了 Encode/Decode
> protocol 部分似乎还是 Encode/Decode
> 
> 是之后还有其他的未完成的部分吗

完成了。obfs部分改成了Read和Write的考虑是，除了tls1.2以外，其他的obfs逻辑都比较简单，不需要使用到dst和src两个buffer，所以就改成了Read/Write，避免在Decode里面`dst.ReadFrom(src)`

2021-02-09 14:51 UTC, Kr328 commented on component/ssr/obfs/tls1.2_ticket_auth.go
> +		c.ticketBuf[u] = make([]byte, bufLen)
既然这个 map 只在这个方法里使用 能不能抠一抠内存 做成局部变量

2021-02-09 14:52 UTC, Kr328 commented on component/ssr/obfs/tls1.2_ticket_auth.go
> +		c.ticketBuf[u] = make([]byte, bufLen)
并且代码里做了数次查询 性能未必比 []byte 好 (

2021-02-09 16:21 UTC, goomadao commented on component/ssr/obfs/tls1.2_ticket_auth.go
> +		c.ticketBuf[u] = make([]byte, bufLen)
可行，刚刚看了下服务端的逻辑，没有对这部分进行校验，https://github.com/Dreamacro/clash/pull/1189/commits/9462056909de33176f296b71af767f2d9b0a91be 改成了直接随机读，[libev也是这么实现的](https://github.com/shadowsocksrr/shadowsocksr-libev/blob/master/src/obfs/tls1.2_ticket.c#L223-L226)

2021-02-13 11:02 UTC, Dreamacro requested changes
这些是我看到的一些疑问或问题，在弄明白后应该就可以合并了

2021-02-13 17:30 UTC, goomadao commented on adapters/outbound/shadowsocksr.go
> +	var (
因为protocol需要用到IV，streamCipher的IV可以通过`ObtainWriteIV`方法获得，dummy的IV是`nil`。而`core.Cipher.StreamConn`只有三种情况：
- shadowstream.Conn(stream cipher)
- shadowaead.Conn(aead cipher)
- `ssr.obfs.StreamConn`返回的`net.Conn`(dummy)

根据net.Conn的具体类型才能确定获取IV的具体方法或者抛出类型错误

2021-02-13 17:32 UTC, goomadao commented on component/ssr/obfs/random_head.go
> +	c.Write(nil)
https://github.com/Dreamacro/clash/pull/805#discussion_r454298753
具体代码可能有更改，不过思路都是一样的

2021-02-13 17:50 UTC, goomadao commented on component/ssr/obfs/random_head.go
> +	c.buf = append(c.buf, b...)
从代码语义上看，这里的header是一串随机的bytes再加上其经过crc32的长度，server端收到header并且长度校验通过后也会返回一串随机bytes，然后会在`Read`中调用`c.Write(nil)`，这时候才会send这个buffer。不清楚在sent header后直接send这个buffer能不能正常通信（之后试一下

2021-02-14 01:58 UTC, Dreamacro commented on adapters/outbound/shadowsocksr.go
> +	var (
这里的 streamConn 是从 0 开始发送协议，理论上应该用不到之前的 IV。比如 relay 里先是 wrap 了一层 shadowsocks，又想 wrap 一层 ssr，这里的 net.Conn 并不是只有这三种类型

2021-02-14 08:04 UTC, goomadao commented on adapters/outbound/shadowsocksr.go
> +	var (
IV都是在protocol的`packAuthData`方法中使用，而在`packAuthData`中获取不到当前连接的IV，所以只能在初始化连接的时候就将IV放到protocol对应的struct中，`ObtainWriteIV`在第一次调用时会初始化IV以供之后使用，并不是之前的IV。`ssr.cipher.StreamConn`返回的`net.Conn`确实应该只有三种情况，因为`core.PickCipher`在不抛出err的情况下只有三种return情况
- [dummy](https://github.com/Dreamacro/go-shadowsocks2/blob/master/core/cipher.go#L85) -> 对应 `ssr.obfs.StreamConn`返回的`net.Conn`([因为将传入的net.Conn原样返回](https://github.com/Dreamacro/go-shadowsocks2/blob/master/core/cipher.go#L149))
- [aeadCipher](https://github.com/Dreamacro/go-shadowsocks2/blob/master/core/cipher.go#L106) -> 对应 [shadowaead.Conn](https://github.com/Dreamacro/go-shadowsocks2/blob/master/core/cipher.go#L129)
- [streamCipher](https://github.com/Dreamacro/go-shadowsocks2/blob/master/core/cipher.go#L117) -> 对应 [shadowstream.Conn](https://github.com/Dreamacro/go-shadowsocks2/blob/master/core/cipher.go#L140)

2021-02-14 08:10 UTC, goomadao commented on adapters/outbound/shadowsocksr.go
> +		} else {
https://github.com/Dreamacro/clash/pull/1189/commits/cca2c9d031a3f5f859650faabc27c5767046310a Done

2021-02-14 08:29 UTC, goomadao commented on component/ssr/obfs/http_simple.go
> +	packURLEncodedHeadData(buf, headData)
这里需要对所有字符都进行编码，而`QueryEscape`对未保留字符并不会进行编码，因此不能用

2021-02-14 08:33 UTC, goomadao commented on component/ssr/protocol/auth_aes128_sha1.go
> +			log.Errorln("Wrong protocol-param for %s, only digits are expected before ':'", a.salt)
https://github.com/Dreamacro/clash/pull/1189/commits/d8a1101a91058d4b80aca6b5e51a35a103e99c8f Done

2021-02-14 08:33 UTC, goomadao commented on component/ssr/protocol/base.go
> +		log.Errorln("New cipher error: %s", err.Error())
https://github.com/Dreamacro/clash/pull/1189/commits/d8a1101a91058d4b80aca6b5e51a35a103e99c8f Done

2021-02-14 09:05 UTC, goomadao commented on component/ssr/obfs/random_head.go
> +	c.buf = append(c.buf, b...)
不能正常通信，需要保持现在的代码逻辑

2021-02-14 10:26 UTC, Dreamacro commented on adapters/outbound/shadowsocksr.go
> +	var (
我觉得你可能没明白我的意思，这个函数甚至会被其他代理调用：即传入的 net.Conn 并不一定是下面 DialContext 所调用。所以所有 ssr 相关的初始化工作都应该在这个函数内执行，而不是断言传入的 net.Conn 类型

2021-02-14 10:27 UTC, Dreamacro commented on adapters/outbound/shadowsocksr.go
> +	var (
我看了一下代码 发现我确实看错了...

2021-02-14 10:45 UTC, Dreamacro commented on component/ssr/obfs/random_head.go
> +	c.buf = append(c.buf, b...)
> > 从代码语义上看，这里的 header 是一串随机的 bytes 再加上其经过 crc32 的长度，server 端收到 header 并且长度校验通过后也会返回一串随机 bytes，然后会在`Read`中调用`c.Write(nil)`，这时候才会 send 这个 buffer。不清楚在 sent header 后直接 send 这个 buffer 能不能正常通信（之后试一下
> 
> 不能正常通信，需要保持当前的代码逻辑

看来服务端并不是纯粹的流式处理 TCP

2021-02-14 17:20 UTC, goomadao commented on adapters/outbound/shadowsocksr.go
> +	var (
https://github.com/Dreamacro/clash/pull/1189/commits/50ef8084f777dd75d107e53671239e5be8a5bbd5 Done

2021-02-15 06:20 UTC, Dreamacro approved these changes

2021-02-15 06:21 UTC, Dreamacro commented
@Kr328 你这边有什么其他觉得需要改动的地方么

2021-02-15 06:25 UTC, Kr328 commented
> @Kr328 你这边有什么其他觉得需要改动的地方么

应该没什么了 (

2021-02-15 06:32 UTC, merged

2021-02-15 06:34 UTC, Dreamacro commented
Thanks for contribution

2021-02-16 07:05 UTC, HynoR commented
> 其实主流的ssr后端可以参考一下这个
> https://github.com/Anankke/shadowsocks-mod
> 毕竟这是现在用的最多的SSPanel-Uim面板的配套后端，其他的后端虽然大部分没开源，但是应该是和这个后端对外表现是一致的
> 
> 它这个版本的后端实现的是对的
> https://github.com/Anankke/shadowsocks-mod/blob/manyuser/shadowsocks/udprelay.py#L208
> https://github.com/Anankke/shadowsocks-mod/blob/manyuser/shadowsocks/obfsplugin/auth.py#L1199

其实拿这个服务端做clash对ssr协议是否断流其实并不好。

这个后端虽然很多圈子内的人在用，但因为ssr年久失修的问题，本身就存在残缺的情况。
如果某些机场使用此后端进行搭建，尤其是单端口多用户方式
- 在有大文件上传的时候会直接吃满CPU 并且可能会中断上传的情况。 在部分docker非官方打包的版本中这个问题尤其严重，具体可以用这个后端搭建的节点自行telegram上传一个图片试试，一般都会出现直接中断，并且服务器cpu跑满且无法继续正常运行。
- 这个python后端只吃单核，没办法多核，在性能不足的时候也会造成中断。
- 内存占用会随着运行时长逐步上升。吃满服务器内存后直接崩溃造成中断

**个人认为在此次修复之后如果还有用户提issue反馈从机场订阅的ssr断流问题，其优先考虑的应该是那个机场的后端问题而不归咎于clash本身的问题**

2021-02-16 07:55 UTC, Dreamacro commented
@HynoR 最好的方法就是不再使用 ssr，然而这个方法由于各种原因看起来并不可行 🌚

2021-02-16 08:03 UTC, wwqgtxx commented
> @HynoR 最好的方法就是不再使用 ssr，然而这个方法由于各种原因看起来并不可行 🌚

从使用层面来说，机场订阅一直没办法抛弃ssr的一个主要原因是：别的协议对单端口多用户的支持都多多少少有些缺陷。vmess/vless/trojan它们虽然原生支持多用户，但是他们都是UoT，对游戏用户不友好；目前支持ss多用户的后端都是通过http-obfs插件支持的，依然是不支持udp转发；当然目前已经有基于ss aead来实现单端口多用户的轮子了（ 比如[mmp-go](https://github.com/qv2ray/mmp-go) ），但好像还没有什么机场后端支持，而且靠这种使用每个密钥逐个尝试解密包头的方式对资源的消耗在用户量较大时增长过于明显。所以有不少机场兜兜转转的又换回年久失修的ssr了🌚

2021-02-16 10:00 UTC, HynoR commented
> > @HynoR 最好的方法就是不再使用 ssr，然而这个方法由于各种原因看起来并不可行 🌚
> 
> 从使用层面来说，机场订阅一直没办法抛弃ssr的一个主要原因是：别的协议对单端口多用户的支持都多多少少有些缺陷。vmess/vless/trojan它们虽然原生支持多用户，但是他们都是UoT，对游戏用户不友好；目前支持ss多用户的后端都是通过http-obfs插件支持的，依然是不支持udp转发；当然目前已经有基于ss aead来实现单端口多用户的轮子了（ 比如[mmp-go](https://github.com/qv2ray/mmp-go) ），但好像还没有什么机场后端支持，而且靠这种使用每个密钥逐个尝试解密包头的方式对资源的消耗在用户量较大时增长过于明显。所以有不少机场兜兜转转的又换回年久失修的ssr了🌚

毕竟没啥东西是绝对完美的，只有等大佬们去填坑了_(:з」∠)_

2021-02-16 15:21 UTC, goomadao commented
> > 其实主流的ssr后端可以参考一下这个
> > https://github.com/Anankke/shadowsocks-mod
> > 毕竟这是现在用的最多的SSPanel-Uim面板的配套后端，其他的后端虽然大部分没开源，但是应该是和这个后端对外表现是一致的
> > 它这个版本的后端实现的是对的
> > https://github.com/Anankke/shadowsocks-mod/blob/manyuser/shadowsocks/udprelay.py#L208
> > https://github.com/Anankke/shadowsocks-mod/blob/manyuser/shadowsocks/obfsplugin/auth.py#L1199
> 
> 其实拿这个服务端做clash对ssr协议是否断流的测试其实并不好。
> 
> 这个后端虽然在圈子内被广泛使用，但因为ssr年久失修的问题，本身就存在残缺的情况。
> 如果某些机场使用此后端进行搭建，尤其是单端口多用户方式
> 
> * 有大文件上传的时候会直接吃满CPU 并且可能会中断上传。 在部分docker非官方打包的版本中这个问题尤其严重，具体可以用这个后端搭建的节点自行telegram上传一个图片试试，一般都会出现直接中断，并且服务器cpu跑满且无法继续正常运行。
> * 这个python后端只吃单核，没办法多核，在性能不足的时候也会造成中断。
> * 内存占用会随着运行时长逐步上升。吃满服务器内存后直接崩溃造成中断
> 
> **个人认为在此次修复之后如果还有用户提issue反馈从机场订阅的ssr断流问题，其优先考虑的应该是那个机场的后端问题而不归咎于clash本身的问题**

之前的ssr实现由于时间比较紧，没有仔细理解ssr源码，确实存在一些问题，在winscp上通过scp上传文件基本百分百触发。这次重构的测试方法是

1. winscp正常scp
2. git clone Linux kernel正常完成
3. speed test完成测速
4. 能正常通过代理，使用dig完成dns查询
5. 在上述测试过程中代理所有其他网络请求，不出现（影响使用体验的）错误

保证ssr能正常使用（尽量不出现断流这些影响使用体验的问题），可能存在的一些没测试到的小问题以后再慢慢修吧