Feature: lookup domain through assigned nameserver
Dreamacro/clash pull request #1406
Opened 2021-05-16 13:02 UTC by icpz

Sometimes we need clash lookup domains via specific nameservers. Here is an example configuration:
```yaml
dns:
  assign-nameserver:
    enable: true
    listen: '0.0.0.0:53'
    assign-nameserver:
      'www.baidu.com': '114.114.114.114'
      '+.internal.crop.com': '10.0.0.1'
```

This feature may resolve issues like https://github.com/Dreamacro/clash/issues/1376 .

It seems that we need a more appropriated term here, instead of `assign-nameserver`.

2021-05-17 13:03 UTC, icpz commented
Now the config looks like:
```yaml
dns:
  resolver-rule:
    enable: true
    listen: '0.0.0.0:53'
    assign-nameserver:
      'www.baidu.com': '114.114.114.114'
      '+.internal.crop.com': '10.0.0.1'
```

2021-05-18 09:57 UTC, Dreamacro requested changes

2021-05-18 09:57 UTC, Dreamacro commented on config/config.go
> +	rule := make(map[string]dns.NameServer)
prefer `map[string]dns.NameServer{}`

2021-05-18 09:57 UTC, Dreamacro commented on config/config.go
> +			rule[domain] = nameservers[0]
The domain is not verified here, which make config unexpected

2021-05-18 09:57 UTC, Dreamacro commented on config/config.go
> +	if dnsCfg.ResolverRule, err = parseResolverRule(&cfg); err != nil {
should be just pass through a map?

2021-05-18 09:57 UTC, Dreamacro commented on dns/resolver.go
> +		return []dnsClient{}
`return nil` is enough

2021-05-18 09:57 UTC, Dreamacro commented on dns/resolver.go
> +	record := r.rule.Search(strings.TrimRight(domain, "."))
`msgToDomain` already trim right question

2021-05-18 10:33 UTC, icpz commented on config/config.go
> +			rule[domain] = nameservers[0]
Sorry I didn't get this... Could you please give an example?

2021-05-19 03:07 UTC, Dreamacro approved these changes

2021-05-19 03:17 UTC, merged