HTTP: refactor http proxy
Dreamacro/clash pull request #1443
Opened 2021-06-14 06:21 UTC by Kr328

1. 将 http 代理实现从 tunnel 里拿出来 使 tunnel 仅需要处理 TCP 和 UDP
2. 使用 http.Client 管理多个出站连接
    https://github.com/Dreamacro/clash/blob/6091fcdfece557284ef519816111e86537d56775/tunnel/connection.go#L83-L84
3. 修正 Host 头问题

2021-06-14 11:55 UTC, Dreamacro requested changes

2021-06-14 11:55 UTC, Dreamacro commented on listener/http/proxy.go
> +	for keepAlive {
这段的逻辑相对复杂，感觉是可以优化的

2021-06-14 11:55 UTC, Dreamacro commented on listener/http/proxy.go
> +	activated := cache == nil // disable authenticate if cache is nil
变量名和实际的内容似乎是相反的

2021-06-14 11:55 UTC, Dreamacro commented on listener/http/server.go
> +func NewWithAuthenticate(addr string, in chan<- C.ConnContext, authenticate bool) (*Listener, error) {
这里拆出单独的一个函数是为了什么？

2021-06-14 11:55 UTC, Dreamacro commented on listener/http/server.go
> +		closed:   false,
是 zero value 的话，可以不写

2021-06-14 11:55 UTC, Dreamacro commented on listener/mixed/mixed.go
> +	http.HandleConn(bufConn, in, nil)
为什么这里的 cache 是 nil

2021-06-14 11:56 UTC, Dreamacro commented
这个重构是否会触发之前的几个奇怪的问题？有测试过么

2021-06-14 14:06 UTC, Kr328 commented on listener/mixed/mixed.go
> +	http.HandleConn(bufConn, in, nil)
测试的时候忘记恢复了 (

2021-06-14 14:06 UTC, Kr328 commented on listener/http/server.go
> +func NewWithAuthenticate(addr string, in chan<- C.ConnContext, authenticate bool) (*Listener, error) {
留个坑 Android 用 (

2021-06-14 14:07 UTC, Kr328 commented on listener/http/proxy.go
> +	activated := cache == nil // disable authenticate if cache is nil
true 是经过认证的 是 "激活的" 如果 cache 是 nil 就默认是已激活的

2021-06-14 14:08 UTC, Kr328 commented
之前的奇怪问题有什么 (

mixed 和 http 都测试过

以及百度问题也

2021-06-14 19:13 UTC, Kr328 commented on listener/http/proxy.go
> +	for keepAlive {
现在的话 是尽量复用 返回 response 的逻辑

新的提交稍微拆解了一些东西 应该能降低理解难度

2021-06-14 19:13 UTC, Kr328 commented on listener/http/proxy.go
> +	activated := cache == nil // disable authenticate if cache is nil
改成 trusted 了

2021-06-14 19:13 UTC, Kr328 commented on listener/http/server.go
> +		closed:   false,
改了

2021-06-14 19:17 UTC, Kr328 commented
这样的实现相对于原来的实现会多一次复制

outbound -> relay buffer -> request/response

如果 tunnel 能抽象成对外暴露 tunnel.DialContext 这样的 API 的话 就能减少这样的开销

2021-06-15 04:12 UTC, Dreamacro reviewed
tunnel 需要的 DialContext 是什么意思？目前所有的 Proxy 都支持了 DialContext

2021-06-15 04:17 UTC, Dreamacro commented
#1387 的这个问题还会出现么

2021-06-15 04:56 UTC, Kr328 commented on listener/http/client.go
> +	defaultClientTimeout = time.Minute
这个 timeout 包括整个 http 调用的过程 包括 后来的 response 复制 (https://golang.org/pkg/net/http/#Client

一分钟甚至感觉有些短

但是如果没有超时 假设远程服务一直不发送数据的话 可能这个连接就无法被关闭
就算是 inbound 提前关闭了连接 以现在的逻辑是没办法取消的 (除非再开一条 goroutine 来检测 inbound

我还是再试试能不能检查 inbound 状态来取消 request

2021-06-15 05:00 UTC, Kr328 commented
> tunnel 需要的 DialContext 是什么意思？目前所有的 Proxy 都支持了 DialContext

是指 github.com/Dreamacro/clash/tunnel 这个包

不再使用 TCPIn() <- C.ConnContext 然后 io.CopyBuffer 这样的方式来转发
而是提供 DialContext 直接返回 net.Conn 让输入端决定如何转发

2021-06-15 05:09 UTC, Dreamacro commented
@Kr328 不太能这样，现在从 inbound 到 tunnel 以及和 outbound 的分离是有意设计成这样的。我认为 inbound 不应该直接操作 outbound。

这样也方便作为一个 library 来使用: https://github.com/Dreamacro/clash/wiki/use-clash-as-a-library

2021-06-15 06:48 UTC, Kr328 commented
> #1387 的这个问题还会出现么

outbound 的连接现在由 http.Client 管理 应该不会出现这个问题 (我自己测试是没有问题的

2021-06-15 06:49 UTC, Kr328 commented on listener/http/client.go
> +	defaultClientTimeout = time.Minute
检测 inbound 连接的话 实现起来有一些些麻烦 还是继续用超时吧 (

不过超时设置改成近似 http.DefaultClient 了

2021-06-15 09:09 UTC, Dreamacro commented on listener/http/client.go
> +	defaultClientTimeout = time.Minute
timeout 应该是建立连接的过程吧，如果是 response 复制的话，正常的数据流动应该不算是 timeout 的吧

2021-06-15 09:13 UTC, Dreamacro approved these changes

2021-06-15 09:13 UTC, merged

2021-06-15 09:14 UTC, Dreamacro commented
终于把 plain http 这个毒瘤变成普通的 socket 了 🎉

2021-08-24 11:53 UTC, ibigbug commented on listener/http/hack.go
> +func ReadRequest(b *bufio.Reader, deleteHostHeader bool) (req *http.Request, err error)
请问这里为什么要这样hack？这个 deleteHostHeader有哪里用到吗？