[Feature] SOCKS4/SOCKS4A Inbound Support
Dreamacro/clash pull request #1491
Opened 2021-07-17 04:55 UTC by xjasonlyu

该PR主要是加入了SOCKS4/SOCKS4A的兼容性支持，其中SOCKS4/5共同享有一个SOCKS端口。

SOCKS4的代理接入支持主要是为了一些兼容性：
- WINDOWS默认socks代理下有时就会使用v4而不是v5
- 浏览器如Firefox，在设置了socks代理并有一些需要ws的场景下会默认使用v4请求：#504
- 一些远古时期的工具仅支持SOCKS4代理

2021-07-17 05:00 UTC, xjasonlyu commented
cURL可用性测试：

- `curl -v -x socks4://127.0.0.1:1080 http://223.5.5.5`
- `curl -v -x socks4a://127.0.0.1:1080 http://google.com`

2021-07-17 12:23 UTC, Dreamacro commented
* windows 版本包括 win10 吗？如果不包括的话我觉得不需要兼容
* firefox 最新版还会走 socks4 吗？同上
* 远古时期的工具都有哪些，有很常用的么？同上

2021-07-17 13:52 UTC, xjasonlyu commented
- 包括win10（因为微软好像怎么更新都不管这块），如果仅设置套接字代理的话直接就没法上网了，因为他默认就是socks4的版本
- MacOS下设置了socks代理，Firefox依然会使用socks4协议去请求代理
- 这个一下想不起来了==，

2021-07-17 14:31 UTC, Dreamacro requested changes

2021-07-17 14:31 UTC, Dreamacro commented on listener/socks/tcp.go
> +		return
应该 close conn

2021-07-17 14:31 UTC, Dreamacro commented on transport/socks4/socks4.go
> +		code = 90 // request granted
code 是不是应该写成和 cmd 类似的 const？

2021-07-17 14:31 UTC, Dreamacro commented on transport/socks4/socks4.go
> +		return errors.New("IPv6 not supported")
通用的 error 也放到全局上的 var 里？

2021-07-17 14:31 UTC, Dreamacro commented on transport/socks4/socks4.go
> +	binary.BigEndian.PutUint16(dstPort[:], port)
这里不需要在这里写到一个 [2]byte 吧？

2021-07-17 14:31 UTC, Dreamacro commented on transport/socks4/socks4.go
> +	copy(dstIP[:], ip.To4())
这里也不需要有一个 [4]byte

2021-07-17 14:31 UTC, Dreamacro commented on transport/socks4/socks4.go
> +	case 91:
这里也是

2021-07-17 14:31 UTC, Dreamacro commented on transport/socks4/socks4.go
> +func splitHostPort(addr string) (string, uint16, error) {
这里也只用一次，没必要吧？

2021-07-17 14:31 UTC, Dreamacro commented on transport/socks4/socks4.go
> +	copy(dstIP[:], req[4:8])
这里为什么不直接
```golang
distIP := req[4:8]
dstPort := req[2:4]
```

2021-07-17 22:31 UTC, xjasonlyu commented on transport/socks4/socks4.go
> +		return errors.New("IPv6 not supported")
这些error只出现一次，需要放全局var嘛

2021-07-18 03:19 UTC, xjasonlyu commented on listener/socks/tcp.go
> +		return
✅

但mixed那里的这个怎么不用closeConn

2021-07-18 03:20 UTC, xjasonlyu commented on transport/socks4/socks4.go
> +	copy(dstIP[:], req[4:8])
可以，本来觉得这么写直观一点。

2021-07-18 03:25 UTC, xjasonlyu commented on transport/socks4/socks4.go
> +	binary.BigEndian.PutUint16(dstPort[:], port)
为什么不需要，下面2字节的dstPort要作为回复发回给client的

2021-07-18 06:32 UTC, Dreamacro requested changes

2021-07-18 06:32 UTC, Dreamacro commented on transport/socks4/socks4.go
> +	if isReservedIP(dstIP[:]) {
dstIP 和下面的 dstPort 都不需要再次切片了吧？

2021-07-18 06:32 UTC, Dreamacro commented on transport/socks4/socks4.go
> +	req.Write(dstPort[:])
可以直接 `binary.Write(req, binary.BigEndian, uint16(port))`

2021-07-18 06:32 UTC, Dreamacro commented on transport/socks4/socks4.go
> +	if !ip.IsUnspecified() && subnet.Contains(ip) {
这里是不是直接 `return !ip.IsUnspecified() && subnet.Contains(ip)`

2021-07-18 06:32 UTC, Dreamacro commented on listener/socks/tcp.go
> +		HandleSocks4(conn, in)
这里也可以直接传入 bufConn 的，readUntilNull 那边会更加友好

2021-07-18 06:33 UTC, Dreamacro commented on transport/socks4/socks4.go
> +	binary.BigEndian.PutUint16(dstPort[:], port)
下面回了

2021-07-18 08:05 UTC, Dreamacro approved these changes

2021-07-18 08:09 UTC, merged

2021-07-18 08:10 UTC, Dreamacro commented
Τhanks for your hard work 🥳