logging actual port
Dreamacro/clash pull request #1492
Opened 2021-07-18 07:13 UTC by ayanamist

如果在配置文件中使用 `127.0.0.1:0` 会由操作系统分配一个端口号，但现在的clash代码，不会把这个被分配的端口号暴露出来，这个改动简单的把这个端口号打印到日志中；由操作系统选择端口号，几乎不会碰到端口号冲突的问题，方便集成到其他应用程序中。

2021-07-18 08:16 UTC, Dreamacro requested changes

2021-07-18 08:16 UTC, Dreamacro commented on hub/route/server.go
> +		err = http.Serve(l, r)
我觉得这里可以把 这个 http.Serve 放这个 if 外面

2021-07-18 08:16 UTC, Dreamacro commented on listener/http/server.go
> -	return l.address
如果 Listener 结构体里的 address 不再使用了，可以一起删掉了

2021-07-18 08:19 UTC, Dreamacro commented
另外值得一提的是，0 在除了 `external-controller` 之外的配置是有实际意义的，目前请求修改端口的 API 如果传入了一个 0 端口，则代表关闭的意思

2021-07-18 09:48 UTC, ayanamist commented
> 另外值得一提的是，0 在除了 `external-controller` 之外的配置是有实际意义的，目前请求修改端口的 API 如果传入了一个 0 端口，则代表关闭的意思

那这里是否要同时判断下addr？毕竟可以传入 127.0.0.1:0 这样的地址的。你觉得fine的话，我同时修改下，我做的集成，没有哪个固定的端口是确保可用的，所以统统监听0端口是最好的选择

2021-07-18 11:09 UTC, ayanamist commented on hub/route/server.go
> +		err = http.Serve(l, r)
抱歉，这里没看明白，这里要确保 `l` 不是null才能Serve的，放到外面的话怎么guard呢？

2021-07-18 11:20 UTC, ayanamist commented on listener/http/server.go
> -	return l.address
全部改掉了

2021-07-18 11:22 UTC, ayanamist commented
看到 `portIsZero` 的使用了，我按我的想法改了下，现在port是负数才会被关掉，这个貌似修改api了，需要你评估下了，我觉得把`0`当关闭不是太合适，毕竟所有OS都是认`port==0`时端口随机这个逻辑的。

2021-07-18 14:49 UTC, Dreamacro commented
改 API 算是一个比较大的 break change，包括 dashboard 之类的 GUI 可能都需要更新。clash for windows 可能也依赖了这个「特性」

2021-07-19 02:17 UTC, ayanamist commented
> 改 API 算是一个比较大的 break change，包括 dashboard 之类的 GUI 可能都需要更新。clash for windows 可能也依赖了这个「特性」

我先把 `portIsZero` 相关的改动给revert了，其余保留了，是不是可以先合并这部分，`portIsZero` 的逻辑再单独讨论？

2021-07-19 04:07 UTC, Dreamacro commented on hub/route/server.go
> +		err = http.Serve(l, r)
这里还是有 err 先 return，把 if 里逻辑往外放，尽量把主逻辑放在一个缩进少的地方

2021-07-19 04:23 UTC, ayanamist commented on hub/route/server.go
> +		err = http.Serve(l, r)
改了。本来我觉得写两个`log.Errorln`不是很好看。

2021-07-19 06:06 UTC, Dreamacro approved these changes

2021-07-19 06:07 UTC, merged

2021-07-19 06:08 UTC, Dreamacro commented
感谢 👍

2021-07-31 16:24 UTC, CoelWu commented
@Dreamacro D大能否review下，总感觉这是个不正常的表现。（此前并未出现，最新dev复现）

2021-07-31 16:39 UTC, Dreamacro commented
@CoelWu fixed

2021-07-31 16:45 UTC, CoelWu commented
> @CoelWu fixed

感谢D大