增加一种dns类型
Dreamacro/clash pull request #1495
Opened 2021-07-19 07:07 UTC by ayanamist

不同场所的dns不一样，在公司用公司的dns，在家里有路由器的ISP DNS，其中公司DNS可能会包含公司内网的域名解析，因此是不能使用公共DNS（例如114）来替代的。但目前clash的dns设置，只能使用一些静态的dns配置，无法根据当前网络状况切换dns。

考虑到系统dns其实已经能根据DHCP信息自动更新DNS配置，因此这里希望增加一种DNS类型 `local://` 将相关DNS请求交给系统处理，来解决这个问题。

使用方式为，在`dns`那一节中配置`nameserver: ["local://"]`

2021-07-19 07:09 UTC, ayanamist commented
另外这里想问一下 Makefile 里为啥要显式设置 `CGO_ENABLED=0` ？是遇到什么问题吗？pure go的resolver无法和系统其他组件共享dns缓存的。

2021-07-19 07:19 UTC, Dreamacro commented
这个 local 有个很严重的问题，比如增强模式下，几乎所有的流量都会经过 clash，当然也包括这里的 net.DefaultResolver。所以当系统的 dns 设置为 clash 提供的 dns 时，会造成 lookback 问题

2021-07-19 07:24 UTC, Dreamacro commented
clash 目前完全不依赖 cgo，go 的 dns resolver 完全无法自定义，所以目前的实现是自己做这个 resolver 包括 dial 时也是（我也不想，但是目前 golang 只能这么做）。既然都脱离了这一体系，完全可以自己做 dns 缓存，也可以使用更好地 dns 过期策略。

不依赖 CGO 跨平台也友好。

2021-07-19 07:33 UTC, ayanamist commented
> 这个 local 有个很严重的问题，比如增强模式下，几乎所有的流量都会经过 clash，当然也包括这里的 net.DefaultResolver。所以当系统的 dns 设置为 clash 提供的 dns 时，会造成 lookback 问题

增强模式的用户需要自己设置bypass，让clash的流量不再回环过来，例如通过iptables的owner模块，或者不使用这个local，这个local模式是opt-in的，注明使用场景就好了，介意的可以不用吧。

2021-07-19 07:36 UTC, ayanamist commented
> clash 目前完全不依赖 cgo，go 的 dns resolver 完全无法自定义，所以目前的实现是自己做这个 resolver 包括 dial 时也是（我也不想，但是目前 golang 只能这么做）。既然都脱离了这一体系，完全可以自己做 dns 缓存，也可以使用更好地 dns 过期策略。
> 
> 不依赖 CGO 跨平台也友好。

理解了，不过windows和android上的dns解析其实都没有pure go方案的，而这两者刚好是desktop和mobile的最大份额。

2021-07-19 07:41 UTC, Dreamacro commented
现在的方式就是 pure go 的，可能最大的区别就是不读 host 吧

2021-07-19 07:42 UTC, ayanamist commented
> 现在的方式就是 pure go 的，可能最大的区别就是不读 host 吧

要不先看下这个PR本身，这个PR和 `CGO_ENABLED=0` 其实没啥关系。

2021-07-19 12:04 UTC, Kr328 commented
看了一下 PR 的实现是用的 net.Resolver 进行 DNS 解析

**在有 cgo 的情况下**

所有平台都会优先使用 cgo 进行解析 (除非设定 PreferGo

unix 系:
https://github.com/golang/go/blob/a66190eceeea63aab0b5410ae3222454e5e0cd96/src/net/lookup_unix.go#L91-L105

windows:
https://github.com/golang/go/blob/a66190eceeea63aab0b5410ae3222454e5e0cd96/src/net/lookup_windows.go#L85-L169

**在没有 cgo 的情况下**

windows 与有 cgo 行为一致
unix 系 会尝试读系统的 DNS 配置文件再使用 Go 进行解析 (Android 除外
Android 就只会去读取 /etc/hosts

**用 cgo 解析可能带来的问题**

cgo 解析时 socket 不经过 go 
clash 无法控制其 LocalAddr 及 interface 
也无法发送给 其他进程打上 mark (Android 需要
由此 无法根据进程区分直连流量的平台上 会引起回环问题 
1. Windows 需要 LocalAddr
2. MacOS 需要 interface
3. Android 需要将 fd 发送给 netd

仅有 Linux 平台能使用 uid 或 cgroup 区分进程选择特定路由表

2021-07-19 12:07 UTC, Kr328 requested changes

2021-07-19 12:07 UTC, Kr328 commented on dns/local.go
> +	resolver := net.DefaultResolver
这个 resolver 应该指定 Dial 字段 用 dialer.DialContext

2021-07-19 13:50 UTC, ayanamist commented
@Kr328 android上是必须打开CGO支持的，而且要用NDK的CC来编译。
另外这个特性是opt-in的，默认不会用，文档里写清楚增强模式会有问题即可，没必要因噎废食吧。毕竟不是一定要用clash提供的增强模式的，我自己买的proxifier是没有这些回环问题的，作为一个opt-in的特性不用要求那么高吧。

2021-07-19 13:55 UTC, ayanamist commented on dns/local.go
> +	resolver := net.DefaultResolver
修改了

2021-07-19 14:52 UTC, Kr328 commented
> @Kr328 android上是必须打开CGO支持的，而且要用NDK的CC来编译。
> 另外这个特性是opt-in的，默认不会用，文档里写清楚增强模式会有问题即可，没必要因噎废食吧。毕竟不是一定要用clash提供的增强模式的，我自己买的proxifier是没有这些回环问题的，作为一个opt-in的特性不用要求那么高吧。

按照我的观点 既然提供了相关功能 (tun) 那就应该保证 应用内的其他功能不会破坏它的实现

Android 我可以自己补丁 但是 Windows 呢

至于 proxifier 它不使用 tun 而使用系统的 WFP

2021-07-19 15:18 UTC, ayanamist commented
Windows和macOS可以像以前一样使用，这个`local://`并不是强制开启的，而且tun功能是闭源的，开源版是完全不受影响的。

2021-07-19 15:23 UTC, ayanamist commented
另外我回顾了一下讨论，在目前 `CGO_ENABLED=0` 的编译前提下，使用了 `dialer.DialContext` 后好像也不会出现 @Kr328 你所说的冲突问题呀，能详细说明一下吗？

2021-07-19 15:55 UTC, Kr328 commented
premium 功能是 开源版的超集 既然存在这个功能 那就会被合并入 premium

Windows 上面写了 无论有没有 cgo 都会使用系统的 API (syscall 包) 进行解析

而使用系统 API 进行 DNS 查询的 socket 不能被 clash 控制 

Windows 不像是 Linux 有多个路由表 可以为不同进程配置不同路由表

如果在 Windows 下将 tun 配置为默认网关 
就需要为所有 clash 出站 socket 配置 本地地址 (LocalAddr) 才能使其选择路由表上的另一个默认网关 
上面写了 如果通过系统 API 则无法控制 socket 这部分 DNS 流量最终会经过 tun 路由再次进入 clash

至于 tun 的配置 除了 Linux 没有自动配置默认网关的实现外 macOS/Windows/Freebsd 都能通过 添加一段简单的配置来实现 对于一个 cli 来说还不算是傻瓜吗
```yaml
tun:
  enable: true
  stack: system
  auto-route: true 
  auto-detect-interface: true
```

2021-07-19 16:01 UTC, ayanamist commented
那你觉得我PR中提到的DNS变化的场景该如何解决？go官方在win下强制依赖cgo也是因为获取dns配置这部分用pure-go实现并不容易。

2021-07-19 16:03 UTC, Kr328 commented
> 那你觉得我PR中提到的DNS变化的场景该如何解决？go官方在win下强制依赖cgo也是因为获取dns配置这部分用pure-go实现并不容易。

就是因为没法解决才到现在都没有添加类似功能 不然早加上了

2021-07-19 16:05 UTC, Kr328 commented
读取系统 DNS 的话
1. unix 族可以读 /etc/resolv.conf
2. Android 可以通过 JNI 注入
3. **Windows 没有办法**

读取 DNS 还得考虑将 系统 DNS 配置成 clash 的 DNS port 的问题

2021-07-19 16:05 UTC, ayanamist commented
那我觉得是不是应该变换下思路，毕竟每个opt-in类型的新功能的增加都要100%兼容已有所有场景，代价是巨大的。

2021-07-20 02:33 UTC, ayanamist commented
仔细思考了一下，这里担心的回环场景其实可以规避，但和直接发请求的场景还不太一样。看不到tun支持的代码，只能做一些猜想。

只讨论上面有分歧的windows下使用`local://`的场景。

分情况讨论：

1. 在系统里设置了dns为127.0.0.1，且让clash dns也监听在`127.0.0.1:53`上面，此时无论怎么处理无论在什么OS上无论是否用tun，只要用了`local://`，就会死循环，原理导致的，就是需要让用户去掉`local://`的使用。
2. 在系统里设置了dns为其他机器，让clash dns运行在了其他机器上，显而易见不会有问题。
3. 未在系统里设置dns，clash dns无所谓是否监听（反正都没人用），系统不用tun，显而易见也不会有问题，这就是我的场景。
4. 未在系统里设置dns，clash dns无所谓是否监听（反正都没人用），系统用tun，这里需要细化：
    1. 不带类似badvpn tun2socks的dnsgw的能力，即不解析dns包，直接当普通udp透传出去，dns解析产生的udp query会经过clash，但此时不会在clash内部经过clash dns模块，而是根据rules里的配置情况直接出去了，**不会死循环**
    2. 带dnsgw能力，会解析dns包，dns解析的udp query会经过clash dns，如果这里配置了`local://`则会有新的请求产生且再次经过tun回到clash dns，产生 @Kr328 担心的回环问题，这里解法如下
        1. 只配置了一个`local://`未配置其它，则不要把这个udp query劫持到clash dns模块，而是当普通udp包放出去
        2. 还配置了其它nameserver，则让`local://`主动报错，让其它nameserver生效

由上可见，并不需要LocalAddr支持，而且这个思路应该也不局限在windows上。

2021-07-20 08:33 UTC, Kr328 commented
local 这样最大的问题就在 tun 上

tun 有个 dns-hijack 你认为是用来干什么的
tun 是一个 L3 层设备 它只能从流量中获取 **来源 IP/目的 IP/来源端口/目的端口**
clash 的是一个基于规则的代理应用 规则支持域名匹配 那么这个域名如何从 L3 中获取 没错 就是 DNS
dns-hijack 就是从流量中嗅探劫持 DNS 流量 所以才能从 目的 IP 推断出访问域名
正正好命中你提到的最坏的情况

另外 你说的 **不应该局限在 Windows 上** 和 之前提到的 **份额最大的两台平台** 有冲突

再有 现在使用 DHCP 获取自动配置的 DNS 的实现已经在实验阶段了 用这个方案不仅能规避 cgo 回环问题 也能防止本机设置 DNS 回环问题 是相对来说的较优解

2021-07-20 08:55 UTC, ayanamist commented
> local 这样最大的问题就在 tun 上
> 
> tun 有个 dns-hijack 你认为是用来干什么的
> tun 是一个 L3 层设备 它只能从流量中获取 **来源 IP/目的 IP/来源端口/目的端口**
> clash 的是一个基于规则的代理应用 规则支持域名匹配 那么这个域名如何从 L3 中获取 没错 就是 DNS
> dns-hijack 就是从流量中嗅探劫持 DNS 流量 所以才能从 目的 IP 推断出访问域名
> 正正好命中你提到的最坏的情况
> 
> 另外 你说的 **不应该局限在 Windows 上** 和 之前提到的 **份额最大的两台平台** 有冲突
> 
> 再有 现在使用 DHCP 获取自动配置的 DNS 的实现已经在实验阶段了 用这个方案不仅能规避 cgo 回环问题 也能防止本机设置 DNS 回环问题 是相对来说的较优解

你好像并没有看我回复的内容，你说的dns-hijack就是我说的有dnsgw的场景，我解释了该怎么做，最坏场景我并没有放弃。

另外有冲突的那些话，是顺着你的意图往下说来试图解决冲突而已。

听起来你们要绕过Windows的网络，自己再触发一次DHCP以此获取DNS吗，我觉得问题会很多，很多DHCP服务器对DHCP request并不是幂等的，擅自触发一次很可能导致网络中断，而且什么时候再触发一次DHCP探测呢，这个时机很难控制，要接入Windows的API来监听network change事件吗，还是轮询，轮询会有时效性问题，监听的话，我自己有个程序会做这个事情，代码你们可以参考 https://gist.github.com/LiamHaworth/72f96c28fc90936904ba70ae5299218f 总的来说还是太复杂，祝你们好运。

2021-07-20 09:01 UTC, Kr328 commented
只需要向网络内广播一次 dhcpinform 获取一次 ack 就行了 概念验证也通过了 并不需要去使用平台提供的 DHCP API

2021-07-20 09:11 UTC, ayanamist commented
> 只需要向网络内广播一次 dhcpinform 获取一次 ack 就行了 概念验证也通过了 并不需要去使用平台提供的 DHCP API
> 
> DHCP 本身只是 udp 协议 完全可以使用 net.PacketConn 实现
> 即使不使用 dhcpinform 也完全可以伪造一个虚假的 mac 地址请求 IP 完全不会干扰到操作系统

不要伪造mac地址，dhcp是可以按mac地址给不同client广播不同的dns的。

另外我说的就是时机问题，你必须要监听系统事件才知道网络变化了，要重新触发一次inform，不然换个wifi，网就不通了。

2021-07-20 11:22 UTC, Dreamacro commented
当 dns enable 为 true 时，实际上就脱离了 go 原本的那套域名解析机制，全部使用 `miekg/dns` 托管域名解析。为了兼容「系统」DNS 查询，实际上最好的方式是拿到「系统的 DNS」，由于系统 DNS 可能被人为或者 GUI 软件修改，所以从 DHCP 拿取 DNS 地址是目前来说最好的方式：完全可控、不用担心被修改、接入方便。

2021-07-20 11:53 UTC, ayanamist commented
> 当 dns enable 为 true 时，实际上就脱离了 go 原本的那套域名解析机制，全部使用 `miekg/dns` 托管域名解析。为了兼容「系统」DNS 查询，实际上最好的方式是拿到「系统的 DNS」，由于系统 DNS 可能被人为或者 GUI 软件修改，所以从 DHCP 拿取 DNS 地址是目前来说最好的方式：完全可控、不用担心被修改、接入方便。

我有点糊涂了，dns模块的目的不是为了解决dns污染问题吗？自己绕开原本的域名解析机制只是个手段，不是目的吧

2021-07-23 06:46 UTC, beyondkmp commented
windows目前看网上还是有方法的，只不过现在没有windows，测试不了
```
package main

import (
	"fmt"
	"github.com/kbinani/win"
	"unsafe"
)

func main(){
	dnss := getNetworkParams()
	fmt.Println(dnss)
}

func getNetworkParams() []string {
	dns := []string{}
	info := win.FIXED_INFO_W2KSP1{}
	size := uint32(unsafe.Sizeof(info))
	r := win.GetNetworkParams(&info, &size)
	if r == 0 {
		for ai := &info.DnsServerList; ai != nil; ai = ai.Next {
			d := fmt.Sprintf("%v.%v.%v.%v", ai.Context&0xFF, (ai.Context>>8)&0xFF, (ai.Context>>16)&0xFF, (ai.Context>>24)&0xFF)
			dns = append(dns, d)
		}
	} else if r == win.ValueOverflow {
		newBuffers := make([]byte, size)
		netParams := (win.PFIXED_INFO)(unsafe.Pointer(&newBuffers[0]))
		win.GetNetworkParams(netParams, &size)
		for ai := &netParams.DnsServerList; ai != nil; ai = ai.Next {
			d := fmt.Sprintf("%v.%v.%v.%v", ai.Context&0xFF, (ai.Context>>8)&0xFF, (ai.Context>>16)&0xFF, (ai.Context>>24)&0xFF)
			dns = append(dns, d)
		}
	}
	return dns
}
```

2021-07-23 07:04 UTC, ayanamist commented
Windows上并不是获取不了dns，而是不能每次都去获取，隔一段时间再获取的话，网络变了DNS变了，这个间隔里网络会不通

2021-09-06 15:08 UTC, Dreamacro commented
close because of #1509

2021-09-06 15:08 UTC, closed without merging