[Feature] DNS: add dhcp type dns
Dreamacro/clash pull request #1509
Opened 2021-07-24 10:10 UTC by Kr328

添加一个从 DHCP 中获取 DNS 并用于解析的 DNS 类型

**测试平台**
- [x] Linux
- [ ] Windows
- [ ] MacOS

2021-07-25 07:49 UTC, icpz commented
macOS 11.5, DHCP server dnsmasq 2.80 tested ok.

2021-07-27 05:27 UTC, Dreamacro requested changes

2021-07-27 05:27 UTC, Dreamacro commented on component/dialer/dialer.go
> +func dualStackDialContextWithHook(dialerHook DialerHookFunc, dialHook DialHookFunc, ctx context.Context, network, address string) (net.Conn, error) {
实践起来 hook 的方式并不特别友好，特别是想支持特定网卡，是不是改成 functional options 的方式会好一些

2021-07-27 05:27 UTC, Dreamacro commented on dns/dhcp.go
> +			d.cacheTTL--
这个 cacheTTL 起到了什么作用？

2021-08-23 08:28 UTC, Kr328 commented on component/dhcp/conn_linux.go
> +const (
是有重合

2021-08-23 08:31 UTC, Kr328 commented on dns/dhcp.go
> +			d.cacheTTL--
这个的逻辑是

1. 每 20s 检查接口 IP 是否发生变化
2. 每 60 次 IP 相同则强制重新获取 DNS (用于极端情况下可能 DNS 变化而 IP 没有变化

2021-08-30 11:01 UTC, icpz requested changes

2021-09-02 03:59 UTC, Kr328 commented on component/dhcp/conn.go
> +	return dialer.ListenPacket(ctx, "udp4", listenAddr, dialer.WithInterface(ifaceName), dialer.WithAddrReuse(true))
fixed

2021-09-02 03:59 UTC, Kr328 commented on component/dhcp/dhcp.go
> +	go receiveAck(conn, inform.TransactionID, result)
fixed

2021-09-02 03:59 UTC, Kr328 commented on component/iface/iface.go
> +func PickIPv6Addr(addrs []*net.IPNet) (*net.IPNet, error) {
fixed

2021-09-03 16:32 UTC, icpz requested changes

2021-09-03 16:32 UTC, icpz commented on component/iface/iface.go
> +		if (destination == nil && !addr.IP.IsLinkLocalUnicast()) || (destination != nil && addr.Contains(destination)) {
这个条件有点（下面 IPv6 也是）问题，如果 destination 是个 global unicast 的地址比如 8.8.8.8，然后这个网卡上是内网地址，那就都被这个条件给过滤掉了…具体条件感觉可以这样：
1. 若是 dest 是 link local 或者 private address 就优先选 addr.Contains(dest) 的
2. 若 dest 是个 global unicast 地址，那么就选第一个非 link local 的 addr

@Dreamacro D 大怎么看，需要这样的策略么

2021-09-03 16:32 UTC, icpz commented on component/dialer/bind_others.go
> +
这里得判断一下 err，不然 addr 是 nil 的话后面 addr.IP 会 panic

2021-09-05 10:23 UTC, Dreamacro requested changes

2021-09-06 06:30 UTC, Kr328 commented on dns/dhcp.go
> +			d.err = err
在这里

![image](https://user-images.githubusercontent.com/39107975/132170676-8fff58a5-c5ba-4f71-a8b7-9e3484fbaf3d.png)

2021-09-06 06:30 UTC, Kr328 commented on component/dialer/options.go
> +type Config struct {
fixed

2021-09-06 06:31 UTC, Kr328 commented on component/dialer/bind_others.go
> +
fixed

2021-09-06 06:31 UTC, Kr328 commented on component/iface/iface.go
> +		if (destination == nil && !addr.IP.IsLinkLocalUnicast()) || (destination != nil && addr.Contains(destination)) {
fixed

2021-09-06 06:32 UTC, Kr328 commented
@Dreamacro @icpz 

我这里没有测试环境 (指 DHCP 不响应 
测一测新的 commit

2021-09-06 12:25 UTC, icpz approved these changes
已在 darwin/linux/windows (amd64) 平台测试。
目前在 freebsd 上不能工作，原因是 freebsd 平台上接受广播包似乎需要使用 bpf

2021-09-06 15:07 UTC, Dreamacro approved these changes

2021-09-06 15:07 UTC, merged