Feature: mark on socket
Dreamacro/clash pull request #1705
Opened 2021-10-30 18:03 UTC by fakeboboliu

## 目的

为 Linux 下的出站连接提供一个随 Proxy Group 可变的 mark，从而使后续的策略路由变得可行。

同时此方案可作为 #1118 和 #1383 的一个平台相关解决方案（只要他们用 Linux 作为主网关）。

## 使用示例

在代理组中指示 mark：
```yaml
proxy-groups:
  - name: DD
    type: select
    proxies:
      - DIRECT
      - Proxy1
    mark: 23
```

在 rule 中使用需要的组，使用 iptables 或 iproute2 匹配对应的 mark 进行后续的策略路由即可。

如使用：
```
ip route add default dev pppoe1 table 2
ip rule add fwmark 23 lookup 2
```
来实现对上面这个代理组指定使用 pppoe1 设备。

## 限制

因为需要使用 `SO_MARK` 标记，必须 `Linux 2.6.25+`，并且有 `CAP_NET_ADMIN` 权限。

## 未完成部分

healthcheck 部分尚欠缺对应的调整，healthcheck 不会添加 mark 以使用策略路由。

顺便，因为在这个实现中 mark 的设置是通过 metadata 的，如果能使用 script 来修改 metadata 应当能实现更为灵活的控制（分时段等）。

2021-10-31 00:28 UTC, Dreamacro commented
与躺着 premium 仓库的自定网卡（dev base）可能有冲突（包括代码实现上）,要不等我推到这仓库的时候你再看看？

2021-10-31 01:57 UTC, fakeboboliu commented
> 与躺着 premium 仓库的自定网卡（dev base）可能有冲突（包括代码实现上）,要不等我推到这仓库的时候你再看看？

好

2021-11-03 14:34 UTC, Dreamacro commented
@fakeboboliu #1714

2021-11-07 09:50 UTC, Dreamacro commented
@fakeboboliu #1714 已经 merge 到 dev，我看到对 structure 进行了改动，是出现了什么问题么？

2021-11-08 04:02 UTC, fakeboboliu commented
@Dreamacro 

#1714 中的 config parse 并未完全修复，我考虑拆到一个单独的 pr 去

对其他 structure 的修改是为了提供 v2ray/trojan over grpc 兼容

2021-11-08 04:10 UTC, Dreamacro commented
要不先处理一下这里的冲突？

2021-11-08 05:57 UTC, Dreamacro requested changes

2021-11-08 05:57 UTC, Dreamacro commented on component/dialer/options.go
> +type Options struct {
为什么要改成大写，这里不需要让外部知道 options 的存在

2021-11-08 05:57 UTC, Dreamacro commented on component/dialer/mark_nonlinux.go
> +func bindMarkToDialer(mark int, dialer *net.Dialer, _ string, _ net.IP) {}
如果不支持的系统是不是可以打一个一次性的警告日志？

2021-11-08 05:57 UTC, Dreamacro commented on adapter/outbound/vmess.go
> +func (v *Vmess) getTransport(opts ...dialer.Option) *http2.Transport {
我觉得暂时没必要把这个复杂化，让这些带有多路复用的先「不复用」

2021-11-08 06:22 UTC, fakeboboliu commented on component/dialer/options.go
> +type Options struct {
为了让下面的 transport 可以根据 options 复用，如果暂时不管的话就可以再小写回去

2021-11-08 06:34 UTC, fakeboboliu commented on adapter/outbound/vmess.go
> +func (v *Vmess) getTransport(opts ...dialer.Option) *http2.Transport {
这个改回去了，让我们观察下吧

虽然我也觉得没啥用，但是看到有一部分没法覆盖到就怪难受的（

2021-11-08 06:56 UTC, Dreamacro commented on component/dialer/options.go
> +	AddrReuse     bool
这里也没必要大写了

2021-11-08 07:09 UTC, fakeboboliu commented on component/dialer/options.go
> +	AddrReuse     bool
忘记改了（

2021-11-08 08:48 UTC, Dreamacro approved these changes

2021-11-08 08:59 UTC, merged

2021-12-07 08:00 UTC, m2acgi commented
@fakeboboliu 大佬，求助, tun2socks + clash:
- 主网卡名称 ens18, ip 192.168.0.1
- tun2socks 网卡名称 tun0, ip 172.16.0.1, 默认 route 已改为 tun0
- clash 设置  `routing-mark: 6666`

已设置 route 和 rule, 没有效果，是哪里没设置对呢？

```
ip route add default via 192.168.0.1 dev eth0 table 2
ip rule add fwmark 6666 lookup 2
```