fix tls handshake unexpected timeout.
Dreamacro/clash pull request #1893
Opened 2022-01-09 14:32 UTC by thank243

This a temporary solution. Waiting official fixed it.

2022-01-12 02:28 UTC, icpz requested changes

2022-01-12 02:28 UTC, icpz commented on transport/gun/gun.go
>  		if err := cn.Handshake(); err != nil {
`HandshakeContext` will perform the actual handshake, so we should check it's error and remove the unnecessary `Handshake`:

```go
if err := cn.HandshakeContext(ctx); err != nil {
...
}
```

2022-01-12 02:28 UTC, icpz commented on transport/gun/gun.go
> +		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
We can add a constant `DefaultTLSTimeout = 10 * time.Second` in `constant/adapters.go`, and reference it here:
`ctx, cancel := context.WithTimeout(context.Background(), constant.DefaultTLSTimeout)`

2022-01-12 15:16 UTC, thank243 commented
add TLS timeout const in constant.

2022-01-13 11:25 UTC, icpz requested changes

2022-01-13 11:25 UTC, icpz commented on transport/gun/gun.go
> +	C "github.com/Dreamacro/clash/constant"
Sorry but please don't change the order and empty lines of the imports.

2022-01-15 11:31 UTC, icpz approved these changes
LGTM

2022-01-15 11:33 UTC, merged

2022-01-15 11:33 UTC, Dreamacro commented
Thanks!