Chore: add apis
Dreamacro/clash pull request #1917
Opened 2022-01-18 04:11 UTC by Kr328

添加一些 API 方便使用 HTTP API 和 作为 library

1. 增加接口 `ProxyGroupAdapter`, 为 library 提供获取 当前 proxy-group 状态的方法
2. 为全部的 ProxyGroup 的 HTTP API 增加 providers 字段
3. 为全部的 Provider 暴露 UpdatedAt 和 Destroy 方法 (作为 Library 和 Android 需要使用

2022-01-27 12:19 UTC, Dreamacro requested changes

2022-01-27 12:19 UTC, Dreamacro commented on adapter/outboundgroup/relay.go
> +		for proxy != nil {
不太明白这里的改动是为了什么

2022-01-27 12:19 UTC, Dreamacro commented on constant/provider/interface.go
> +	UpdatedAt() *time.Time
返回一个 time.Time 比 *time.Time 要好吧？

2022-02-21 11:04 UTC, Kr328 commented on constant/provider/interface.go
> +	UpdatedAt() *time.Time
因为 fetcher 里也是 *time.Time

```Go
type fetcher struct {
	name      string
	vehicle   types.Vehicle
	updatedAt *time.Time
	ticker    *time.Ticker
	done      chan struct{}
	hash      [16]byte
	parser    parser
	onUpdate  func(interface{})
}
```

结构里要不要顺便一起改

2022-02-21 11:04 UTC, Kr328 commented on adapter/outboundgroup/relay.go
> +		for proxy != nil {
因为 Unwrap 被移动到 `ProxyGroupAdapter` 上了

(在普通的 Proxy 支持 Unwrap 怎么想都不合理 (

2022-04-28 02:19 UTC, closed without merging