[F] Fixed the problem that the full path was incorrectly encoded due …
Dreamacro/clash pull request #2213
Opened 2022-07-09 18:04 UTC by LJea

Fixed the problem that the full path was incorrectly encoded due to missing QueryParam

Clash LOG:time="2022-07-09T22:36:32+09:00" level=warning msg="[TCP] dial DEF (match Match/) to [domain]:443 error: dial [domain]:443 error: 404 Not Found"
Server LOG:[ip] - - [09/Jul/2022:22:34:59 -0400] "GET /[path]%3F[query] HTTP/1.1" 404 1457 "-" "Go-http-client/1.1"

As seen in the logs "?" was encoded as "%3F" by the URL, which resulted in a 404 error

2022-07-10 03:50 UTC, Dreamacro requested changes

2022-07-10 03:50 UTC, Dreamacro commented on transport/vmess/websocket.go
> +		return nil, fmt.Errorf("parse url[%s]: %s", c.Path, err)
`fmt.Errorf("parse url %s error: %w", c.Path, err)` seems better

2022-07-10 03:50 UTC, Dreamacro commented on transport/vmess/websocket.go
> +
no multiple empty line plz

2022-07-10 04:39 UTC, Dreamacro commented
please fix linter issue

2022-07-10 05:57 UTC, LJea commented
Processing

2022-07-10 06:54 UTC, Dreamacro approved these changes

2022-07-10 06:56 UTC, merged

2022-07-10 06:56 UTC, Dreamacro commented
thanks a lot 👏

2022-10-20 05:16 UTC, Web5530top reviewed
ljea:dev