Feature: allow opt-in of symmetric NAT for UDP
Dreamacro/clash pull request #2410
Opened 2022-11-11 13:51 UTC by ssz66666

## 背景

目前对于类似VMess的面向流的，只支持对称型NAT模式的代理，Clash的UDP转发处理是不正确的。

按Clash现有对UDP NAT表的处理，对于**来源Socket地址相同**的外发UDP包，是复用同一`PacketConn`进行处理的，即全部采用锥形NAT的方式处理。
https://github.com/Dreamacro/clash/blob/de264c42a811b609a63423d99945543c6ae1f1aa/tunnel/tunnel.go#L192-L205

对VMess这种完全按照TCP流方式进行UDP转发，而非将一个来源Socket地址映射到代理服务器上一个端口的协议，只能使用对称型NAT的方式。即对于**来源Socket地址与目的Socket地址均相同**的外发UDP包，才认为可以复用同一`PacketConn`做转发。

https://github.com/Dreamacro/clash/blob/de264c42a811b609a63423d99945543c6ae1f1aa/adapter/outbound/vmess.go#L356-L368
在VMess的adapter实现中，一个`PacketConn`实质是一个`Conn`，通过代理实际上只能跟一个对端Socket地址进行收发通信，在`WriteTo`中忽略收到的目标地址，在`ReadFrom`中直接返回底层连接建立时确定的目标地址。

按原有照搬锥形NAT的处理方式，如果尝试用同一本地UDP端口向不同远端UDP地址发包，会将所有UDP包都发往一开始建立PacketConn连接时指定的远端地址。

## PR做出的修改

- 在 `constant.ProxyAdapter`接口中添加了`ShouldUseSymmetricNAT() bool`方法，用于指定代理是否应按对称NAT而不是锥形NAT模式进行UDP转发。
- 在`adapter/outbound.Base`中，添加了`symmnat bool` field，对应`ShouldUseSymmetricNAT`方法的返回值，默认值为`false`。
- 在VMess的outbound adapter指明应使用对称型NAT。
- 在`tunnel/tunnel.go`的`handleUDPConn`处理收到的UDP外发包时，按照匹配的代理支持的NAT类型分别处理：
  - 对于锥形NAT则使用`{代理名}>>{本地Socket地址}`作为NAT Table的键；
  - 对于匹配代理只支持对称NAT时，改用`{代理名}>>{本地Socket地址}-{目标Socket地址}`作为NAT Table的键。

2022-11-12 11:01 UTC, Dreamacro commented
我不认为现在的处理方式是不正确的，它只是 vmess 协议缺陷的一种妥协。

考虑两种 UDP 的使用场景

1. 对于简单的 UDP 通信（如 dns 查询）
现在的处理方式没有什么不妥，vmess 在这种场景下也没什么问题

2. 对于复杂 UDP 使用场景（如 STUN 等）
vmess 本身的协议缺陷：实现了类似 udp tunnel 的功能，但没法实现一个 vmess 连接往不同 udp 地址发包以及无法识别收到包的地址。
我看了一下你的修改，如果我没有理解错的话，你是针对不同的远端地址打开了不同的 vmess 连接。

```


                                                   ┌────────────────────┐
                                     1.1.1.1:10000 │       Vmess        │
                                  ┌────────────────┤                    │
                                  │                │  10.200.1.1:20000  │
                                  │                └────────────────────┘
                                  │
 ┌───────────────────┐            │
 │       Local       │            │
 │                   ├────────────┤
 │ 192.168.1.2:10000 │            │
 └───────────────────┘            │
                                  │
                                  │                ┌────────────────────┐
                                  │                │       Vmess        │
                                  └────────────────┤                    │
                                     2.2.2.2:10000 │  10.200.1.1:20001  │
                                                   └────────────────────┘


```

不说从一个 UDP 套接字变成两个会不会影响程序本身的业务功能，也无法解决从 vmess 监听套接字返回包缺失地址的问题。这个方案不仅没法解决问题（当然也解决不了），还引入了过多的特殊逻辑。

我认为既然 vmess 协议在 UDP 方面存在严重的缺陷，那么就让它能在一些简单的 UDP 场景下使用即可。我看你也研究了这么多，不会不知道 vmess 目前有很大的缺陷，最好的方法当然是换个协议。

唯一一个值得商讨的地方在于，是否应该只发包到第一个地址，丢弃其他发往其他地址的包，这个我没记错的话算是规范里的未定义行为。

2022-11-12 12:50 UTC, ssz66666 commented
> 1. 对于简单的 UDP 通信（如 dns 查询）
> 现在的处理方式没有什么不妥，vmess 在这种场景下也没什么问题

由于绝大多数的用户流量其实都是TCP，很多情况下UDP仅用于DNS解析，修改与否对大多数用户确实也无感知。


> 2. 对于复杂 UDP 使用场景（如 STUN 等）
> ...
> 不说从一个 UDP 套接字变成两个会不会影响程序本身的业务功能

一个实现了对称NAT的路由器/防火墙本来就会做如此处理，对终端程序的影响主要是先Listen后再用同一源Socket地址向不同对端Socket地址发包的场景（如STUN打洞），但由于VMess的协议设计限制，本来也无法实现Full Cone NAT，我理解应该没有影响。

按原有的实现，一律假定外发协议支持Full Cone的话，在使用VMess时是会导致UDP包被发到错误的对端地址的，我认为这样实现是错误的。


> 也无法解决从 vmess 监听套接字返回包缺失地址的问题。这个方案不仅没法解决问题（当然也解决不了）

因为`针对不同的远端地址打开了不同的 vmess 连接`，而每一个新的`vmessPacketConn`是会记录这个Connected Socket对应的对端地址的，所以是能够正确返回这个Connected UDP Socket对应的对端地址的。
在一个实现了对称NAT的路由器/防火墙里，就是要维护 **源端地址 + 对端地址** 与 **实际出向地址**的对应关系的。 （对于Clash来说，出向UDP套接字地址就是个`constant.PacketConn`）。


> 还引入了过多的特殊逻辑

我理解这个特殊逻辑是为了保证正确性，增加了复杂性，可能牺牲了部分UDP转发性能（但性能影响有待benchmark）。


> vmess 目前有很大的缺陷，最好的方法当然是换个协议

这个理解，但有时候对端使用的协议，以及其协议的实现方式不是用户能控制的😂。


> 唯一一个值得商讨的地方在于，是否应该只发包到第一个地址，丢弃其他发往其他地址的包，这个我没记错的话算是规范里的未定义行为。

VMess协议规范里显然没有定义。如果一定要固定按照FullCone NAT来实现UDP的转发，个人认为丢弃会比发包到错误的对端地址要合理。

## 关于NAT UDP 转发逻辑
另外，我认为现在的UDP NAT实现还有一个问题：

现在clash的实现仅仅依靠**来源Socket地址**判断是否复用UDP Socket，没有判断这个对端地址是否应该使用相同的外发出口（或理解为相同的外发的IP地址）。Clash因为支持按照规则匹配出向接口，可以类比为一个multi-homed的网关，所以即使是实现FullCone NAT，也应该考虑根据规则（路由策略）判断以后，使用的外发IP地址是否一致，再判断使用的外发端口。

那么举一个极端的例子：
客户端先ListenUDP `192.168.1.2:10000`，使用这个UDP socket，通过Clash分别向`1.1.1.1:10000`与`2.2.2.2:10000`发包。
假设用户配置规则为：`1.1.1.1`应使用SS1代理，`2.2.2.2`应使用Direct直连。按现有实现，如果客户先先向`1.1.1.1:10000`，后向`2.2.2.2:10000`发包，则会两个包均通过SS1发出，我理解与用户预期的表现是不符合的。

而建议的方案，是同时根据匹配的OutboundAdapter（对应了应该使用的外发IP地址），以及源端套接字地址，来判断使用的外发端口（在实现上就是对应能否复用已有的PacketConn）。
```


                                                   ┌────────────────────┐
                                     1.1.1.1:10000 │       SS1          │
                                  ┌────────────────┤                    │
                                  │                │  10.200.1.1:20000  │
                                  │                └────────────────────┘
                                  │
 ┌───────────────────┐            │
 │       Local       │            │
 │                   ├────────────┤
 │ 192.168.1.2:10000 │            │
 └───────────────────┘            │
                                  │
                                  │                ┌────────────────────┐
                                  │                │       Direct       │
                                  └────────────────┤                    │
                                     2.2.2.2:10000 │  10.210.1.1:20000  │
                                                   └────────────────────┘

1.1.1.1 : SS1
2.2.2.2 : Direct
```

对应PR中：
```go
	var key string
	var strBuilder strings.Builder


	strBuilder.WriteString(proxy.Name())
	strBuilder.WriteString(">>")
	strBuilder.WriteString(packet.LocalAddr().String())


	if !proxy.ShouldUseSymmetricNAT() {
		// For Cone NAT, use outbound adapter name + source address as key
		key = strBuilder.String()
```


但同样，这个仅仅对应了先bind后sendto/recvfrom的**复杂 UDP 使用场景**，是否要为了这些复杂场景来改正UDP转发逻辑，如此修改后会不会影响大多数简单场景用户的体验，还是需要斟酌。我理解这个修改主要是会影响大量使用UDP转发功能，利用TUN/透明代理模式，加速WebRTC/视频会议、外服游戏的用户；对于大部分主要使用TCP的用户应该影响很小。

2022-11-12 13:37 UTC, ssz66666 commented
又思考了一下，如果按照正常的逻辑，改成先选路再选端口，而不是直接用第一次建立连接时的固定出向端口，反倒会造成STUN协议UDP打洞失败🤣STUN协议本身也没有考虑多归的场景。
这么看来，采用“错误”的，固定出向路由方法，配合上把STUN服务器加入直连的规则，反倒是更符合大多数游戏用户预期的~

那上边这条，先选路后NAT的方式（即key中加代理名称），还是不建议修改，哪怕加也只能用“opt-in”模式，但意义真的不是很大，只对于对称NAT提高安全性有意义。

2022-11-12 13:45 UTC, ssz66666 commented
这部分UDP转发的design choice，还是希望能有文档讲解，不然没有仔细想过确实一开始搞不明白~

2022-11-12 15:32 UTC, ssz66666 commented
尝试重写NAT转发逻辑，想实现根据选到的代理是否支持Full Cone来动态地切换到Symmetric NAT，发现因为收到包的时候是不知道这个包要对应那个规则，按照一般用户的期望行为做UDP的NAT，需要忽略规则直接拿【源+目标地址】（对称）/【源地址】（全锥），做两次匹配才行。感觉为了少数情况去让所有UDP包的都多一次判断，没什么必要。

目前想到的方案：

1. 全局统一用FullCone NAT模式（即目前的实现），对于VMess这种协议校验目标地址不同的做丢包处理。这种方式可以解决发错包的问题。
2. 加一个全局选项，允许用户选择FullCone NAT还是Symmetric NAT模式。如果选择了FullCone NAT模式就不使用不支持FullCone NAT模式的代理（如VMess）。

只是单为了解决这个PR里提到的VMess的问题的话，按照方案1做个目标地址校验应该也够了。

方案2考虑可能的受众主要是因为安全性等原因，希望固定使用Symmetric NAT的用户。

2022-11-14 09:35 UTC, Dreamacro commented
你的方式是按包代理，clash 目前的方式是按套接字进行代理。你也说了，代理包可能会走不通的节点导致更多的问题，这在复杂的规则中更容易产生问题，也更难发现和定位。但代理套接字的缺点目前看来就只是根据首包的地址只做一次匹配。

> 全局统一用FullCone NAT模式（即目前的实现），对于VMess这种协议校验目标地址不同的做丢包处理。这种方式可以解决发错包的问题。

我认为这个方法可行，如果你还想改的话可以直接在这个 pr 上进行改动，不需要再开一个新的 pr

2022-11-14 11:55 UTC, ssz66666 commented
> > 全局统一用FullCone NAT模式（即目前的实现），对于VMess这种协议校验目标地址不同的做丢包处理。这种方式可以解决发错包的问题。
> 
> 我认为这个方法可行，如果你还想改的话可以直接在这个 pr 上进行改动，不需要再开一个新的 pr

已更新PR。

写的时候在思考，由于现在对于UDP报文是先在本地做远端地址解析，那么在Clash配置成fake-ip模式时（即先返回fake ip后解析），会不会出现客户端使用域名连接，但由于负载平衡等DNS配置原因，Clash把同一个域名解析成不同IP的情况，导致新的处理方式将报文误丢掉？

2022-11-14 12:20 UTC, Dreamacro commented
这点考虑过，并且 premium 里做过处理，只取 dns 的第一个结果

2022-11-25 09:57 UTC, Dreamacro requested changes

2022-11-25 09:57 UTC, Dreamacro commented on adapter/outbound/vmess.go
> +	if allowedAddr.IP.Equal(destAddr.IP) && allowedAddr.Port == destAddr.Port {
更建议把主要逻辑放在缩进外，错误放缩进里。

2022-11-25 09:57 UTC, Dreamacro commented on adapter/outbound/vmess.go
> +var (
更建议使用全大写的 `UDP`, 另外这里应该过不了 golangci 的 lint 吧？可以使用 make lint 检测

2022-11-25 14:15 UTC, ssz66666 commented on adapter/outbound/vmess.go
> +var (
变量名已改为全大写`UDP`

直接`make lint`会报错，看不懂什么原因。
```
WARN [runner] Can't run linter goanalysis_metalinter: gci: 4:13: expected ';', found "errors" (and 10 more errors) 
ERRO Running error: 1 error occurred:
        * can't run linter goanalysis_metalinter: gci: 4:13: expected ';', found "errors" (and 10 more errors)
```

并且我看其他地方也有类似写法，如：
https://github.com/Dreamacro/clash/blob/ed988dcdc55fb5aa0b76e9fdf4ded38dc5b422bc/component/dhcp/dhcp.go#L1-L17

2022-11-25 14:15 UTC, ssz66666 commented on adapter/outbound/vmess.go
> +	if allowedAddr.IP.Equal(destAddr.IP) && allowedAddr.Port == destAddr.Port {
已修改

2022-11-26 02:25 UTC, Dreamacro commented on adapter/outbound/vmess.go
> +var (
我这里的报错是，var 里如果只有一个变量，就不要用 () 分行。你应该装个新版的 golangci-lint

2022-11-26 02:41 UTC, ssz66666 commented on adapter/outbound/vmess.go
> +var (
我装的是最新版的1.50.1 golangci-lint，但运行会直接报错，请问下使用的版本？

2022-11-26 02:51 UTC, ssz66666 commented on adapter/outbound/vmess.go
> +var (
手动装了gofumpt，已修改了

2022-11-26 03:26 UTC, Dreamacro approved these changes

2022-11-26 03:27 UTC, merged

2022-11-26 03:27 UTC, Dreamacro commented
Thanks