fix: safeConnClose not working
Dreamacro/clash pull request #2463
Opened 2022-12-13 05:25 UTC by wwqgtxx

follow this link: https://stackoverflow.com/a/42703862
>  If you pass any parameters to the defer func (like the 2nd defer function above), those parameters are evaluated when the defer function is deferred, not when they are executed.

2022-12-22 04:20 UTC, Dreamacro requested changes

2022-12-22 04:20 UTC, Dreamacro commented on adapter/outbound/trojan.go
> +			safeConnClose(c, err)
All safeConnClose looks like it needs to pass in the original conn

2022-12-22 04:20 UTC, Dreamacro commented on adapter/outbound/util.go
> +	if err != nil && c != nil {
You should make sure that the incoming conn is non-nil, if not keep the panic behavior for easy debug

2022-12-22 04:20 UTC, Dreamacro commented on adapter/outbound/util.go
> +		_ = c.Close()
Linter allows implicit ignoring errors

2022-12-22 04:42 UTC, Dreamacro approved these changes

2022-12-22 04:42 UTC, merged

2022-12-22 04:42 UTC, Dreamacro commented
Thanks a lot

2023-10-24 00:57 UTC, xjasonlyu commented
I just checked golang's `defer` behavior, considering the following code:

```go
package main

import (
	"errors"
	"fmt"
)

func main() {
	a()
}

func show(err error) {
	if err != nil {
		fmt.Printf("3st defer: %s\n", err)
	} else {
		fmt.Println("3st defer: defer not error")
	}
}

func a() {
	var err error

	defer func() {
		if err != nil {
			fmt.Printf("1st defer: %s\n", err)
		} else {
			fmt.Println("1st defer: defer not error")
		}
	}()

	defer func(err error) {
		if err != nil {
			fmt.Printf("2nd defer: %s\n", err)
		} else {
			fmt.Println("2nd defer: defer not error")
		}
	}(err)

	defer show(err)

	err = errors.New("new error")
	if err != nil {
		return
	}
}
```

Got output:

```
3st defer: defer not error
2nd defer: defer not error
1st defer: new error
```

- Demo here: https://go.dev/play/p/pRSZgLH2nDP

Therefore, I believe this code:

```go
defer func(c net.Conn) {
	safeConnClose(c, err)
}(c)
```

equals to this code:

```go
defer safeConnClose(c, err)
```

Let me know if I get it wrongly. @Dreamacro @wwqgtxx

2023-10-24 01:04 UTC, wwqgtxx commented
@xjasonlyu As shown in your test results, what we need is to maintain the behavior of `1st defer` for `err`, and fix `conn` to be original instead of streamed.

2023-10-24 01:10 UTC, xjasonlyu commented
Oh I see, so it's for getting oldest `c` and latest `err`. Thanks for your explanation!