Feature: add `filter` option to proxy group
Dreamacro/clash pull request #2518
Opened 2023-02-01 21:39 UTC by yaling888

Fix #2509.
Another implementation of the similar pr.
To add a filterable proxy provider to a proxy group, behaves the same as add a file/http proxy provider to a proxy group.
Compared to #1511, it has the same health check behavior as the current proxy group and less memory cost.

Config snippet:
```yaml
...

proxy-groups:
  - name: All
    type: select
    use: &Use
      - Subscription-1
      - Subscription-2

  - name: Geo-HK
    type: url-test
    interval: 600
    tolerance: 100
    url: http://www.gstatic.com/generate_204
    filter: "HongKong|HK|香港"
    use: *Use

  - name: Geo-TW
    type: select
    filter: "Taiwan|TW|台湾"
    use: *Use

  - name: Geo-SG
    type: fallback
    interval: 600
    tolerance: 100
    url: http://www.gstatic.com/generate_204
    filter: "Singapore|SG|新加坡"
    use: *Use

  - name: Geo-JP
    type: load-balance
    interval: 600
    tolerance: 100
    url: http://www.gstatic.com/generate_204
    filter: "Japan|JP|日本"
    use: *Use

  - name: Geo-UK
    type: relay
    filter: "Britain|England|UK|英国"
    use: *Use

  - name: Proxy
    type: select
    use: *Use
    proxies: &Proxy
      - All
      - Geo-HK
      - Geo-TW
      - Geo-SG
      - Geo-JP
      - Geo-UK
      - DIRECT
      - REJECT

  - name: YouTube
    type: select
    use: *Use
    proxies: *Proxy

proxy-providers:
  Subscription-1:
    type: http
    url: "URL1"
    path: ./providers/Subscription-1.yaml
    interval: 10800
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204

  Subscription-2:
    type: file
    path: ./providers/Subscription-2.yaml
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204

...
```

2023-02-17 13:50 UTC, DockerCS commented
希望添加这个功能

2023-02-26 16:07 UTC, shnode commented
等了好久，请问能把这个pr合并到premium核心了么？

2023-02-26 16:09 UTC, DockerCS commented
> 等了好久，请问能把这个pr合并到premium核心了么？

基本不可能了，开发者之前在群里说过，这东西很麻烦

2023-02-27 01:50 UTC, shnode commented
> > 等了好久，请问能把这个pr合并到premium核心了么？
> 
> 基本不可能了，开发者之前在群里说过，这东西很麻烦

那太可惜了，不过我个人尊重开发者的决定

用meta去了，我个人还是很需求这个功能的，谢谢提PR的和楼上各位大佬。

2023-04-06 05:44 UTC, Dreamacro commented
@yaling888 看了一下你的相关实现，你实现了一个 filter 的 provider，这或许是个好的处理方式。

在 group 上实现 filter 主要有一些问题，就是怎么处理 filter 出来结果为空的问题。你在代码里也看到了，目前的代码是基于「group 里一定包含节点」的逻辑去实现的（甚至 dashboard 里也是），目前的 provider 也保证了这一点（filter 结果为空会报错）。我也看到了你在数组为空的时候使用了一个 fallback 的 reject 作为替代，但似乎不如在 filter provider 为空的时候直接塞一个 reject。

另外我看到很多对于 provider 的特殊判断，我的想法是
* filter provider 是一个普通的 provider，当一个 group 同时包含 proxies 及 use 字段时，filter provider 与 CompatibleProvider 一样，不放到 providerMap 下，filter provider 是一个包含 use 字段 provider 的虚 provider
* filter provider 具体的 filter 操作可以从子 providers 里获取并 filter，具体是用 singleflight 或 singledo 获取都可以再考虑，获取结果为空时，塞一个 reject

2023-04-07 06:41 UTC, Dreamacro commented
@yaling888 我不认为 CompatibleProvider（`proxies` 字段）需要做 filter，毕竟是自己写的列表，不需要删了就好了，也不需要 filter。这个时间的话不好定，毕竟感知不到 provider 的更新，不能太短也不能太久

2023-04-07 10:04 UTC, Dreamacro requested changes

2023-04-07 10:04 UTC, Dreamacro commented on adapter/provider/healthcheck.go
> +func (hc *HealthCheck) setProxyFn(proxiesFn func() []C.Proxy) {
也不需要这个，filter provdier 不负责 health check，应该交给子 provider 来做，它只负责 filter

2023-04-07 10:04 UTC, Dreamacro commented on adapter/provider/provider.go
> +		if fp.filterReg != nil {
我理解竟然都封装成 filter provider 了，就不存在没有正则的情况吧？

2023-04-07 10:04 UTC, Dreamacro commented on adapter/provider/provider.go
> +	runtime.SetFinalizer(wrapper, stopFilterableProvider)
也不需要这个逻辑了，因为不用做健康检查，也没有计时器需要自动清理

2023-04-07 10:04 UTC, Dreamacro commented on hub/route/proxies.go
> +			providers := tunnel.Providers()
这个文件也没太理解为什么需要变动

2023-04-08 05:03 UTC, Dreamacro commented on hub/route/proxies.go
> +			providers := tunnel.Providers()
可以放到另一个 pr 里，这个 pr 就只干新增 filter provider 这件事

2023-04-08 05:08 UTC, Dreamacro commented on adapter/provider/provider.go
> +		if fp.filterReg != nil {
不会呀，假设配置文件是这样
```yaml
- name: group1
  proxies: [DIRECT]
  use: [A, B, C]
  filter: 'foo'
```

那么解析后 group1 只存在两个 provider：一个 CompatibleProvider 以及一个 FilterProvider，一个 FilterProvider 中包含 A,B,C 仅作为 FilterProvider 的子 provider 存在，原本 A B C 上的健康检查或者更新机制还是按照各自的执行。

当不存在 filter 字段时，就和原来一样包含 4 个 provider

2023-04-08 05:09 UTC, Dreamacro commented on adapter/provider/healthcheck.go
> +func (hc *HealthCheck) setProxyFn(proxiesFn func() []C.Proxy) {
health check 应该交由原始 provider 来解决，目前 group 内部的健康检查也只针对 proxies 字段（及 CompatibleProvider），不影响 use 中的 provider

2023-04-08 05:11 UTC, Dreamacro commented on adapter/provider/provider.go
> +	return types.Compatible
也许新增一个 Filter 的类型？

2023-04-08 05:17 UTC, Dreamacro commented on adapter/provider/healthcheck.go
> +func (hc *HealthCheck) setProxyFn(proxiesFn func() []C.Proxy) {
> 一个 proxy group 的 health check 行为不应该是统一的吗

事实上不是统一的，和上个回复内容类似，group 配置里的健康检查相关只针对 proxies 字段，这是不包含配置 break change 后的取舍结果

> 这个回复仅限于讨论 health check 应该由谁来做的问题，不代表否认 Clash 目前已实现的功能。

没关系，只要新的实现更优，把实现全部推到重写也没问题

2023-04-08 10:23 UTC, Dreamacro commented on adapter/provider/provider.go
> +	return types.Compatible
啊。。。。我看错了，这个是 VehicleType，那应该不需要改动 😂

2023-04-08 11:23 UTC, Dreamacro approved these changes

2023-04-08 11:23 UTC, merged

2023-04-08 11:24 UTC, Dreamacro commented
Thanks for your patience and modifications, would you mind if I implement a similar logic in premium?