Chore: Allow http to set custom headers
Dreamacro/clash pull request #2647
Opened 2023-03-28 19:16 UTC by RommHui

2023-03-28 20:05 UTC, RommHui commented
An exmaple configuration can be:
`
proxies:
    - name: example
      type: http
      server: 127.0.0.1
      port: 443
      headers:
        User-Agent: chrome
        X-Forwarded-For: 8.8.8.8
`

2023-03-30 05:00 UTC, Dreamacro commented
Can you explain what specific custom header solves your problem?

2023-03-30 05:31 UTC, RommHui commented
@Dreamacro Some http proxies need to verify certain specific request headers, but the original http proxy of Clash does not support custom request headers, which causes the http proxy to fail to operate normally

2023-03-30 07:53 UTC, Dreamacro commented
@RommHui For example? I want to see a practical example.

2023-03-31 07:19 UTC, Dreamacro requested changes

2023-03-31 07:19 UTC, Dreamacro commented on adapter/outbound/http.go
> +	headers := make(http.Header)
perfer `http.Header{}` in this repo

2023-03-31 12:28 UTC, RommHui commented on adapter/outbound/http.go
> +	headers := make(http.Header)
`make(http.Header)` has been changed to `http.Header{}`

2023-03-31 12:33 UTC, merged

2023-03-31 12:34 UTC, Dreamacro commented
Thanks for contributing