Fix: Adjust DNS TTL values based on minimum value
Dreamacro/clash pull request #2706
Opened 2023-04-26 17:50 UTC by KaitoHH

## Problem
The following code uses the TTL of the very first record, as the whole TTL of the response,
https://github.com/Dreamacro/clash/blob/df61a586c9df496c2ab71790534b0cab5d9e47ba/dns/util.go#L28-L33

and these codes further use the previous TTL as the TTL of each entry in answers.
https://github.com/Dreamacro/clash/blob/df61a586c9df496c2ab71790534b0cab5d9e47ba/dns/util.go#L42-L55

This will cause issue when the first answer in the DNS message is greater than the later record.

For example, in the first DNS query
```bash
╰─❯ dog epdg.epc.mnc260.mcc310.pub.3gppnetwork.org A @openwrt.lan
CNAME epdg.epc.mnc260.mcc310.pub.3gppnetwork.org.     5h49m11s   "epdg.epc.geo.mnc260.mcc310.pub.3gppnetwork.org."
    A epdg.epc.geo.mnc260.mcc310.pub.3gppnetwork.org.      17s   208.54.39.163
```

And the second cached query will cause the answer of A type to have a much greater TTL value, which should be expected to expire after 17 seconds after the first query.
```bash
╰─❯ dog epdg.epc.mnc260.mcc310.pub.3gppnetwork.org A @openwrt.lan
CNAME epdg.epc.mnc260.mcc310.pub.3gppnetwork.org.     5h49m07s   "epdg.epc.geo.mnc260.mcc310.pub.3gppnetwork.org."
    A epdg.epc.geo.mnc260.mcc310.pub.3gppnetwork.org. 5h49m07s   208.54.39.163
```

## Resolution
To resolve the issues, this commit adds modify `updateTTL` function that adjusts the TTL values of DNS records based on the minimum TTL value found in the records list instead of the first record. When updating the TTL it calculates the passed delta time and subtracts it to all cached TTL values.  This ensures consistency in the cache expiry time for all records to prevent caching issues.

2023-04-27 03:45 UTC, Dreamacro requested changes

2023-04-27 03:45 UTC, Dreamacro commented on dns/util.go
> +	ttl := records[0].Header().Ttl
Wouldn't it be easier to use https://github.com/samber/lo#minby?

2023-04-27 03:45 UTC, Dreamacro commented on dns/util.go
> +	updateTTL(msg.Answer, ttl)
The ttl here is already minimalTTL delta.

2023-04-27 04:54 UTC, KaitoHH commented on dns/util.go
> +	updateTTL(msg.Answer, ttl)
Here ttl is the value that each record should be set, not the delta value, so we should first calculate the time elapsed (delta = record.TTL - ttl), and then do the subtraction.
Another way of fixing this is to refactor the updateTTL function by passing the delta parameter, but that will be a bit more complex.

2023-04-27 04:58 UTC, Dreamacro commented on dns/util.go
> +	updateTTL(msg.Answer, ttl)
`setMsgTTL(msg.Msg, uint32(time.Until(expireTime).Seconds()))` It's calculated by the expiration time of cache. It's delta.

2023-04-27 05:10 UTC, KaitoHH commented on dns/util.go
> +	updateTTL(msg.Answer, ttl)
I made a mistake in my previous explanation. Let me clarify, at first we should set TTL to be `uint32(time.Until(expireTime).Seconds())`, but this will cause each record to have the same TTL value. 

Let's suppose 5s passed by the time of the first query, so instead of
```bash
╰─❯ dog epdg.epc.mnc260.mcc310.pub.3gppnetwork.org A @openwrt.lan
CNAME epdg.epc.mnc260.mcc310.pub.3gppnetwork.org.     12s  "epdg.epc.geo.mnc260.mcc310.pub.3gppnetwork.org."
    A epdg.epc.geo.mnc260.mcc310.pub.3gppnetwork.org.      12s   208.54.39.163
```

We subtract the common value from each TTL record, so the result will become
 ```bash
╰─❯ dog epdg.epc.mnc260.mcc310.pub.3gppnetwork.org A @openwrt.lan
CNAME epdg.epc.mnc260.mcc310.pub.3gppnetwork.org.     5h49m6s   "epdg.epc.geo.mnc260.mcc310.pub.3gppnetwork.org."
    A epdg.epc.geo.mnc260.mcc310.pub.3gppnetwork.org.      12s   208.54.39.163
```

2023-04-27 05:20 UTC, Dreamacro commented on dns/util.go
> +	updateTTL(msg.Answer, ttl)
In fact the logic of setMsgTTL now sets an absolute value, and there are several other places where it is forced to 1. For these places the current change breaks this behavior

2023-04-27 05:34 UTC, KaitoHH commented on dns/util.go
> +	updateTTL(msg.Answer, ttl)
How about splitting it into two functions so that the fakeip logic is not affected?

2023-04-27 05:35 UTC, Dreamacro commented on dns/util.go
> +	updateTTL(msg.Answer, ttl)
It sounds good to use a new function.

2023-04-28 05:58 UTC, Dreamacro commented on dns/util.go
> +	delta := minimalTTL(records) - ttl
In order to prevent possible 0 and overflow problems, should we need to use `lo.Clamp`? seems we don't need `len(records)` guard?

BTW, run `make lint-fix` to fix some lint issue

2023-04-28 17:41 UTC, KaitoHH commented on dns/util.go
> +	delta := minimalTTL(records) - ttl
`len(records)` is essential since `minimalTTL()` cannot receive an empty slice. Otherwise, `Header()` on empty slice will cause nil pointer panic.

2023-04-29 05:26 UTC, Dreamacro requested changes

2023-04-29 05:26 UTC, Dreamacro commented on dns/util.go
> +		records[i].Header().Ttl = lo.Clamp(records[i].Header().Ttl-delta, 1, records[i].Header().Ttl)
https://github.com/samber/lo#clamp

the first and third parameters is lower and upper bounds.

2023-04-30 04:16 UTC, Dreamacro commented on dns/util.go
> +		records[i].Header().Ttl = lo.Clamp(records[i].Header().Ttl-delta, 1, records[i].Header().Ttl)
sorry, I misread it.

2023-04-30 04:17 UTC, Dreamacro approved these changes

2023-04-30 04:18 UTC, merged

2023-04-30 04:19 UTC, Dreamacro commented
Thanks for the patient modifications, do you mind if I port a similar logic to premium?

2023-04-30 15:07 UTC, KaitoHH commented
> Thanks for the patient modifications, do you mind if I port a similar logic to premium?

No problem.