Refactor: refactor find process
Dreamacro/clash pull request #2781
Opened 2023-06-10 11:55 UTC by Kr328

重构了 PROCESS-NAME/PROCESS-PATH 规则的进程查找

1. 在 metadata 中增加原始目的地址 OriginDst 用于 process 使用四元组查找 inode ，Linux 查找时间从毫秒级变为微秒级
2. Linux 略微修改了进程查找的实现，性能有一点点提升
3. Windows 和 FreeBSD 更换为使用 struct 直接提取字段内容，方便维护
4. Darwin 没有修改，还需要其他人增加 OriginDst 的检查

2023-06-10 12:59 UTC, Dreamacro commented
lint 炸了

2023-06-10 14:56 UTC, Kr328 commented
>  Error: File is not `gci`-ed with --skip-generated -s standard -s prefix(github.com/Dreamacro/clash) -s default --custom-order (gci)
>  Error: File is not `gci`-ed with --skip-generated -s standard -s prefix(github.com/Dreamacro/clash) -s default --custom-order (gci)
>  Error: issues found

这是啥问题

2023-06-11 10:17 UTC, Dreamacro requested changes

2023-06-11 10:17 UTC, Dreamacro commented on adapter/inbound/http.go
> +func NewHTTP(target socks5.Addr, source net.Addr, conn net.Conn, originTarget net.Addr) *context.ConnContext {
参数顺序换一下吧，放第三个

2023-06-11 10:17 UTC, Dreamacro commented on component/process/process_freebsd.go
> +var majorVersion = (func() int {
iife function 不需要括号

2023-06-11 10:17 UTC, Dreamacro commented on component/process/process_freebsd.go
> +	dotIdx := strings.Index(text, ".")
看起来 strings.Cut 更简单一点

2023-06-11 10:17 UTC, Dreamacro commented on component/process/process_freebsd.go
> +		majorVersion = 0
这里 err != nil 时 zerovalue 就是 0

2023-06-11 13:52 UTC, Kr328 commented on adapter/inbound/http.go
> +func NewHTTP(target socks5.Addr, source net.Addr, conn net.Conn, originTarget net.Addr) *context.ConnContext {
改了

2023-06-11 13:52 UTC, Kr328 commented on component/process/process_freebsd.go
> +var majorVersion = (func() int {
改了

2023-06-11 13:52 UTC, Kr328 commented on component/process/process_freebsd.go
> +	dotIdx := strings.Index(text, ".")
改了

2023-06-11 13:52 UTC, Kr328 commented on component/process/process_freebsd.go
> +		majorVersion = 0
改了

2023-06-11 13:53 UTC, Kr328 commented on component/process/process_freebsd.go
> +var majorVersion = (func() int {
改了

2023-06-11 14:05 UTC, Dreamacro commented on component/process/process_test.go
> +	if !assert.NoError(t, err) {
why not `assert.FailNow`

2023-06-11 15:07 UTC, Kr328 commented on component/process/process_test.go
> +	if !assert.NoError(t, err) {
fixed

2023-06-13 15:25 UTC, Dreamacro approved these changes

2023-06-13 15:25 UTC, merged