Feature/port_rule
Dreamacro/clash pull request #2818
Opened 2023-07-03 01:37 UTC by fuyuntt

#2681 
1. [add support for rules based on the local port](https://github.com/Dreamacro/clash/commit/2b06fb83df668c7b106c0c1b043e306e524b81be)
Support for using new rule: "LOC-PORT", this rule matches the local port being listened on by Clash, e.g. "LOC-PORT,7900,Proxies" indicates that incoming requests from the listening port 7900 will be matched by this rule.
2. [support for listening on multiple extra SOCKS ports](https://github.com/Dreamacro/clash/commit/64ea20b142e6880e4fa9fdb3ccb3c7064283ce84)
Support for listening on multiple additional SOCKS ports, where users can apply 'LOC-PORT' rules to perform different actions on incoming requests to these ports.

2023-07-06 03:08 UTC, Dreamacro commented
loc port is a strange name, why not call it Inbound port?

ExtraSocksPort is not generic enough, why can't it support redirect, http, mixed, and so on?

2023-07-06 05:32 UTC, fuyuntt commented
1. `Inbound port` is a good name, I will change it to that. 
2. The reason for not supporting all proxy types is that adding ExtraPorts for each proxy type would increase the code size i would have to write. However, since it seems strange to only support multiple Socks ports, I will also add support for other proxy types. 

I will make these changes and commit in the next week.

2023-07-06 05:59 UTC, Dreamacro commented
> The reason for not supporting all proxy types is that adding ExtraPorts for each proxy type would increase the code size i would have to write

all listeners impl `C.Listener` so we can use a common structure to manage these listeners. It would be nice if these listeners could specify the binding address in the configuration

2023-07-06 15:50 UTC, fuyuntt commented
> > The reason for not supporting all proxy types is that adding ExtraPorts for each proxy type would increase the code size i would have to write
> 
> all listeners impl `C.Listener` so we can use a common structure to manage these listeners. It would be nice if these listeners could specify the binding address in the configuration

good idea, I will try it later.

2023-07-12 15:35 UTC, fuyuntt commented
@Dreamacro done

2023-07-25 05:37 UTC, Dreamacro commented
Sorry for the late reply.

I noticed a lot of new `ExtraXX` fields that were added to the config, but there were problems with the original port listening: the `bind-address` field controls all inbound bind addresses, which is not flexible enough.

Wouldn't it be much better to add a new field, such as 'inbounds', to declare the address and type of the binding? For example:

```yaml
inbounds:
  - type: socks5
    bind-address: 0.0.0.0:7890
  - type: socks5
    bind-address: 192.168.33.1:7891
  # We can even support one line alias
  - socks5://0.0.0.0:7890
```

2023-07-25 05:57 UTC, fuyuntt commented
> Sorry for the late reply.
> 
> I noticed a lot of new `ExtraXX` fields that were added to the config, but there were problems with the original port listening: the `bind-address` field controls all inbound bind addresses, which is not flexible enough.
> 
> Wouldn't it be much better to add a new field, such as 'inbounds', to declare the address and type of the binding? For example:
> 
> ```yaml
> inbounds:
>   - type: socks5
>     bind-address: 0.0.0.0:7890
>   - type: socks5
>     bind-address: 192.168.33.1:7891
>   # We can even support one line alias
>   - socks5://0.0.0.0:7890
> ```
Using new fields might be a good idea, but should we still maintain compatibility with the original fields? If we do maintain compatibility, some issues may be difficult to overcome.
1. what should we do if the configurations in 'inbounds' conflict with the original 'ports' and 'bind-address' configurations?
2. to have the RESTful API return both 'Ports' and 'inbounds' simultaneously, we'd need to store both configurations. This would result in redundant code.

If we don't maintain compatibility, the existing webui would need to be adapted to support the new configuration format.

2023-07-25 11:42 UTC, Dreamacro commented
I don't think there are any problems with keeping the current configuration.

> what should we do if the configurations in 'inbounds' conflict with the original 'ports' and 'bind-address' configurations?

do nothing, The only possible problem is if the GUI "adds" the configuration for you and there is a conflict. The old API is just not flexible enough, and people who will use the new inbound field have special needs, so it's not a problem

> to have the RESTful API return both 'Ports' and 'inbounds' simultaneously, we'd need to store both configurations. This would result in redundant code.

For this problem, I haven't any idea how to return it at the moment, but it can be left unresolved in this pr. We just make sure that adding this configuration itself was the right decision

2023-07-26 05:52 UTC, fuyuntt commented
Okay, then the RESTful interface will only return the 'inbound' configuration and will not return the 'Ports' configuration under the General setting.  

Another question, if the one-line alias form is used during configuration, the RESTful interface can only return the configuration in its regular form. For example, if you configured it as `socks5://0.0.0.0:7890`, the interface retrieval will return `{"type": "socks5", "bind-address": "0.0.0.0:7890"}`. Is this acceptable?

2023-07-26 06:02 UTC, Dreamacro commented
> if you configured it as socks5://0.0.0.0:7890, the RESTful Get will return {"type": "socks5", "bind-address": "0.0.0.0:7890"}. Is this acceptable?

Of course, it could be implemented by a `UnmarshalYAML` struct for both single-line and normal YAML configurations supported

2023-07-26 06:07 UTC, fuyuntt commented
Okay, wait my commit.

2023-07-29 10:57 UTC, fuyuntt commented
@Dreamacro done.

> Of course, it could be implemented by a UnmarshalYAML struct for both single-line and normal YAML configurations supported

I tried using 'UnmarshalYAML'  but encountered some problems, so I simply used `[]any` to accept the inbounds config and then parsed it to implement the functionality.

2023-07-29 15:41 UTC, Dreamacro commented
I pushed a code that solves `UnmarshalYAML`. There's a lot of stuff to change, so the rest of the code needs enough bandwidth to read

2023-07-30 14:08 UTC, Dreamacro requested changes
Except for break and general api, all the other problems are small.

2023-07-30 14:08 UTC, Dreamacro commented on component/process/process_windows.go
> +	"golang.org/x/sys/windows"
clash has its own import ordering rules, just run `make lint-fix` to fix the problem here.

2023-07-30 14:08 UTC, Dreamacro commented on constant/listener.go
> +	listenerType := InboundType(u.Scheme)
It's better to check the address and scheme here to avoid unnecessary errors.

2023-07-30 14:08 UTC, Dreamacro commented on hub/route/inbounds.go
> +func inboundRouter() http.Handler {
Is the implementation of the new api here but breaking the current *-port api inconsistent with the results of our previous discussion?

2023-07-30 14:08 UTC, Dreamacro commented on listener/http/server.go
> +func New(addr string, in chan<- C.ConnContext) (C.Listener, error) {
return the pointer of the struct is always better than returning the interface

2023-07-30 14:08 UTC, Dreamacro commented on listener/listener.go
> +	var needClose []C.Inbound
In clash code, it prefers `variable := []type{}` to avoid returning null when serializing json

2023-07-30 14:08 UTC, Dreamacro commented on test/vmess_test.go
> -		Entrypoint:   []string{"/usr/bin/v2ray"},
What is the reason for removing these two fields here?

2023-07-31 15:06 UTC, fuyuntt commented on listener/http/server.go
> +func New(addr string, in chan<- C.ConnContext) (C.Listener, error) {
returning an interface can standardize the return value of each listener's create method, which allows it to be directly referenced in the following code:
```golang
type tcpListenerCreator func(addr string, tcpIn chan<- C.ConnContext) (C.Listener, error)
var tcpListenerCreators = map[C.InboundType]tcpListenerCreator{
	C.InboundTypeHTTP:   http.New,
	C.InboundTypeSocks:  socks.New,
	C.InboundTypeRedir:  redir.New,
	C.InboundTypeTproxy: tproxy.New,
	C.InboundTypeMixed:  mixed.New,
}
```

2023-07-31 16:11 UTC, fuyuntt commented on test/vmess_test.go
> -		Entrypoint:   []string{"/usr/bin/v2ray"},
At that time, using the previous configuration, the v2ray container couldn't start. I speculated if the latest version of the V2ray image had changed the Cmd. So, I removed the Cmd configuration to use the Cmd in the image, and it started successfully. However, I am now unable to reproduce this issue. In fact, without the Cmd configuration, it cannot run. So, I will revert the commit from that time.

2023-07-31 16:14 UTC, Dreamacro commented on hub/route/inbounds.go
> +func inboundRouter() http.Handler {
The result I expected is to keep all the current api behavior, because it is used by many GUI programs. The new inbound api can only take effect through put config, and other APIs can be implemented later.

2023-07-31 16:18 UTC, Dreamacro commented on test/vmess_test.go
> -		Entrypoint:   []string{"/usr/bin/v2ray"},
On my device, deleting these two lines will cause the test to fail.

2023-07-31 16:34 UTC, Dreamacro commented on component/process/process_windows.go
> +	"golang.org/x/sys/windows"
I reread the sorting rules and you're right. 😂

2023-07-31 17:20 UTC, fuyuntt commented on listener/listener.go
> +	var needClose []C.Inbound
done

2023-07-31 17:20 UTC, fuyuntt commented on test/vmess_test.go
> -		Entrypoint:   []string{"/usr/bin/v2ray"},
done

2023-08-01 02:57 UTC, Dreamacro commented on constant/listener.go
> +	listenerType := InboundType(u.Scheme)
> It feels a bit heavy to put checks like whether the port is occupied in the unmarshal process.

Just check that the port is filled in and check wether scheme is support

2023-08-02 15:52 UTC, fuyuntt commented on constant/listener.go
> +	listenerType := InboundType(u.Scheme)
done

2023-08-03 10:32 UTC, Dreamacro commented
The change looks good.

I noticed that `InboundPort` is currently designed to be of type string, but changing it to uint16 is again limited by the current SrcPort and DstPort. 

This is a legacy issue, I'm thinking about revamping the other two into uint16 as well, I'm thinking about forward compatibility, maybe a separate struct type can be used to solve it?

2023-08-03 10:38 UTC, Dreamacro commented
But that's beyond the scope of this PR, I'll change it later

2023-08-03 10:53 UTC, fuyuntt commented
Why does modifying the data type of the port affect forward compatibility, Isn't it just the type in memory?

2023-08-03 10:59 UTC, Dreamacro commented
> Why does modifying the data type of the port affect forward compatibility, Isn't it just the type in memory?

Metadata is serialized to JSON for output to the API, which is used by the GUI.

2023-08-03 11:01 UTC, Dreamacro commented
At the beginning of the clash, there weren't many places that used uint16 ports, and std libs like net.SplitHostAndPort led to the use of strings instead of uint16 at the beginning.

2023-08-03 11:03 UTC, fuyuntt commented
get

2023-08-03 14:28 UTC, Dreamacro approved these changes

2023-08-03 14:30 UTC, merged

2023-08-03 16:37 UTC, fuyuntt commented
no problem.