VMess HTTP/2 transport support
Dreamacro/clash pull request #903
Opened 2020-08-16 15:12 UTC by xfoxfu

# Feature

Support HTTP/2 transport for VMess.

```yaml
proxies:
  - name: Proxy
    type: vmess
    server: http.example.com
    port: 443
    uuid: 433a65e8-6ab0-49cb-98b6-bde1605f000a
    alterId: 15
    cipher: auto
    network: h2
    h2-opts:
      host:
        - http.example.com
        - http-alt.example.com
      path: /
    tls: true
```

## Implement Details

The client will create a new HTTP/2 connection with system-ca TLS, and perform Read/Write on the connection created. It will randomly choose a host specified in `h2-opts.host`. The existing TLS parameters are all ignored.

# TODOs

- [ ] connect to remote host with `server` instead of using `h2-opts.host`
- [ ] constraint `tls` must be `true`
- [ ] respect existing `tls` settings (Q: what is the `net.Conn` passed to the very first `StreamConn` call? If this question answered, the implement can be enhanced.)

2020-08-16 15:20 UTC, xfoxfu commented on adapters/outbound/vmess.go
> +		c, err = vmess.StreamTLSConn(c, tlsOpts)
This line is currently meaningless, I will remove it with a commit later.

2020-08-17 04:44 UTC, Dreamacro commented
> Q: what is the net.Conn passed to the very first StreamConn call?

It's about the design principles associated with the clash. Each protocol or obfuscation can be treated as a `net.Conn` wrapper

```go
// raw net.Conn
conn, err := net.Dial("tcp", "addr")

// pseudocode
ssConn := ss.StreamConn(conn, ssConfig)

// ss with simple obfs
ssObfsConn := obfs.StreamConn(ssConn, obfsConfig)

// same with vmess
vmessConn := vmess.StreamConn(conn, vmessConfig)

// vmess with ws
vmessWsConn := ws.StreamConn(conn, vmessWsConfig)

// vmess with h2
vmessH2Conn := h2.StreamConn(conn, vmessH2Config)
```

2020-08-17 05:43 UTC, xfoxfu commented
@Dreamacro thanks for your help, I've updated the code to be aligned with this design. I think now the code is ready to be reviewed.

2020-08-25 03:14 UTC, xfoxfu commented
@Dreamacro I have rebased my changes onto `dev`. Is there any problems blocking this to be reviewed? I am quite looking forward to this feature, since HTTP/2 provides better latency than WebSocket.

2020-09-26 11:52 UTC, Dreamacro requested changes
Due to the addition of `staticcheck` to dev branch as a code checker and updated dependencies, please rebase the dev branch and run `staticcheck -- $(go list . /....) ` and `go mod tidy`.

By the way, have you actually tested this http2 feature yet?

2020-09-26 11:52 UTC, Dreamacro commented on component/vmess/h2.go
> +		panic(err)
Why the panic error here? I think we should not panic anything that does not affect the normal operation of the clash.

2020-09-26 12:20 UTC, xfoxfu commented
I have updated the code to remove `panic`. I have already tested `h2` with the following server config:

```json
{
  "inbounds": [
    {
      "port": 25443,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "26de564b-1ff1-4973-b6ad-e643191dbef5",
            "level": 1,
            "alterId": 4
          }
        ]
      },
      "streamSettings": {
        "network": "h2",
        "httpSettings": {
          "path": "/ffd9deb3-cc78-489e-b22c-78930cd32d0b",
          "host": ["127.0.0.1.xip.io"]
        },
        "security": "tls",
        "tlsSettings": {
          "serverName": "127.0.0.1.xip.io",
          "allowInsecure": true,
          "alpn": "h2",
          "certificates": [
            {
              "usage": "encipherment",
              "certificateFile": "/path/to/certificate.crt",
              "keyFile": "/path/to/key.key",
            }
          ],
          "disableSystemRoot": false
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct",
      "settings": {}
    }
  ]
}
```

staticcheck run succeeded with the following output

```console
$ staticcheck -- $(go list . /....)
pattern /....: directory prefix / outside available modules
```

And `go mod tidy` did not suggest any changes.

2020-09-26 12:25 UTC, xfoxfu commented on component/vmess/h2.go
> +		panic(err)
I've updated the code to not panic.

2020-09-26 12:26 UTC, Dreamacro commented
seems something wrong with `staticcheck`, don't worry about CI failed, I would remove the failed test after merge this pr
```
❯ staticcheck -- $(go list ./...)
adapters/outbound/vmess.go:121:3: this value of err is never used (SA4006)
adapters/outbound/vmess.go:201:31: should omit comparison to bool constant, can be simplified to !option.TLS (S1002)
component/vmess/h2.go:62:22: should omit comparison to bool constant, can be simplified to !hc.res.Close (S1002)
```

2020-09-26 12:30 UTC, xfoxfu commented
OK, now staticcheck emits no warnings.

2020-09-26 12:33 UTC, merged

2020-09-26 12:35 UTC, Dreamacro commented
👍 Thank you for your hard work