Feature: split ip to host mapping
Dreamacro/clash pull request #936
Opened 2020-08-31 04:11 UTC by Kr328

分离反解域名的映射 能够比较方便的在热重载配置文件时重用映射

2020-09-01 15:44 UTC, Dreamacro requested changes

2020-09-01 15:44 UTC, Dreamacro commented on component/resolver/mapper.go
> +type HostMapper interface {
是不是这个命名有点奇怪，容易和 hosts 混淆起来

2020-09-01 15:44 UTC, Dreamacro commented on component/resolver/mapper.go
> +	ResolveHost(net.IP) (string, bool)
这个和上面是同一个原因，容易造成 Resolve Hosts 的误解

2020-09-01 15:44 UTC, Dreamacro commented on dns/mapper.go
> +	if pool := h.fakePool; pool != nil {
实际这里稍微有些问题，如果是 Fakeip 模式，并且是 fakeip 的情况下，找不到反映射的时候，就应该返回 false （比如 clash 本身重启丢失了映射）

2020-09-01 15:44 UTC, Dreamacro commented on dns/mapper.go
> +			return h.fakePool.Gateway().Equal(o.fakePool.Gateway())
有点诡异，gateway 一样，但长度可能不一样

2020-09-01 15:44 UTC, Dreamacro commented on dns/middleware.go
> +			msg, err := next(r)
我的理解没错的话，这里修改中间件的部分是为了修改成「洋葱模型」对吗？

2020-09-01 15:44 UTC, Dreamacro commented on dns/middleware.go
> +				mapping.SetWithExpire(ip.String(), host, time.Now().Add(time.Second*time.Duration(ttl)))
即使这里有 cache，是不是还会每次写到 cache 一次？

2020-09-01 15:44 UTC, Dreamacro commented on dns/server.go
> +		D.HandleFailed(w, r)
少了 return

2020-09-01 15:44 UTC, Dreamacro commented on tunnel/tunnel.go
> +		metadata.Host = ""
这里是为什么？

2020-09-01 16:05 UTC, Kr328 commented on dns/middleware.go
> +			msg, err := next(r)
是的

因为上一个中间件可能会需要使用到下一个中间件返回的结果 Resolver -> Mapping

2020-09-01 16:05 UTC, Kr328 commented on dns/middleware.go
> +				mapping.SetWithExpire(ip.String(), host, time.Now().Add(time.Second*time.Duration(ttl)))
会的因为想要 最后解析结果 保留在映射中 在冲突时 可能能解决一部分问题

2020-09-01 16:05 UTC, Kr328 commented on tunnel/tunnel.go
> +		metadata.Host = ""
调试的时候忘记删掉了 (

2020-09-02 14:52 UTC, Dreamacro commented on hub/executor/executor.go
> -	if resolver.DefaultResolver != nil {
为什么删去了这个

2020-09-02 15:23 UTC, Kr328 commented on hub/executor/executor.go
> -	if resolver.DefaultResolver != nil {
个人认为重载的时候应该清除 DNS 缓存 毕竟如果 DNS 产生变更 再次解析结果与缓存不一致

2020-09-02 15:41 UTC, Dreamacro commented on component/fakeip/pool.go
> +func (p *Pool) PatchHosts(o *Pool) {
这个似乎没必要 Patch 直接换了就是了。这么看来 ResolverEnhancer 的 Patch 似乎没必要

2020-09-02 15:43 UTC, Kr328 commented on component/fakeip/pool.go
> +func (p *Pool) PatchHosts(o *Pool) {
fake-ip 会丢映射 (

2020-09-02 15:45 UTC, Kr328 commented on component/fakeip/pool.go
> +func (p *Pool) PatchHosts(o *Pool) {
或者让 fake pool 的 cache 从外部注入 也是可以的 (

2020-09-07 10:00 UTC, Dreamacro commented on component/fakeip/pool.go
> +func (p *Pool) PatchHosts(o *Pool) {
> 或者让 fake pool 的 cache 从外部注入 也是可以的 (

外部注入好一点，最好保持每个地方的 pool 都是同一个而不是多个 pool 各自 patch

2020-09-07 12:18 UTC, Kr328 commented on component/fakeip/pool.go
> +func (p *Pool) PatchHosts(o *Pool) {
想了想还是 直接替换掉整个 Enhancer 好了 (

2020-09-07 15:33 UTC, Dreamacro commented on component/trie/node.go
> +	if n.Data != other.Data {
如果这里塞的是「不可比较」的东西（比如 pointer），那么这个比较就是错误的

2020-09-07 15:42 UTC, Kr328 commented on component/trie/node.go
> +	if n.Data != other.Data {
但是 Golang 似乎没有类似 Comparable 接口 或者默认存在的 equals 函数

对于指针 有没有更好的实现呢

2020-09-07 15:57 UTC, Dreamacro commented on component/trie/node.go
> +	if n.Data != other.Data {
trie 树罢了，直接替换就完事了，不需要 patch。这也不是什么高频操作，没必要那么复杂

2020-09-07 16:01 UTC, Kr328 commented on component/trie/node.go
> +	if n.Data != other.Data {
直接替换的话 在 fake-ip 模式下 Enhancer 永远不会被复用 (

重新载入配置文件时 判断相等 只能为 false 大量映射丢失 (

2020-09-07 16:15 UTC, Dreamacro commented on component/trie/node.go
> +	if n.Data != other.Data {
映射关系可以通过旧的缓存 patch 到新的，然后整个替换掉。

你之前的方法是把新的信息 Patch 到旧的上，这两个方式最大的区别在于：Pool 这个 point 可能在多个地方被用到，旧的缓存 patch 到新的时，我能保证东西被新的替换上去了，反过来则心智负担更大一些

2020-09-14 04:44 UTC, Dreamacro commented on component/fakeip/pool.go
> +func New(r *Range, host *trie.DomainTrie, cache *cache.LruCache) *Pool {
这里内部的 cache length 需要时 2 的倍数，我觉得这点不应该暴露出去。外部在调用的时候并不需要关心我的 cache 是否要 2 的倍数，只关心我需要多少 size。传入 cache 我觉得不是一个很好的做法

2020-09-14 05:57 UTC, Kr328 commented on component/fakeip/pool.go
> +func New(r *Range, host *trie.DomainTrie, cache *cache.LruCache) *Pool {
如果不从外部传入 cache 的话 又会回到最初的 Patch

或者 再包装一层 cache 保证 size * 2 (吗

2020-09-15 16:24 UTC, Dreamacro commented
修改了一点东西，你看看 7603b5f ，可以就合了

2020-09-17 02:48 UTC, merged