Feature: support snell v2 (without connection reuse)
Dreamacro/clash pull request #952
Opened 2020-09-06 09:43 UTC by kamingchan

#920 

base on https://github.com/icpz/snell-server-reversed and https://github.com/icpz/open-snell

2020-09-06 13:59 UTC, Dreamacro requested changes

2020-09-06 13:59 UTC, Dreamacro commented on component/snell/cipher.go
> +type Cipher interface {
aka `github.com/Dreamacro/go-shadowsocks2/shadowaead` shadowaead.Cipher

2020-09-06 13:59 UTC, Dreamacro commented on component/snell/cipher.go
> +	return argon2.IDKey(psk, salt, 3, 8, 1, 32)[:keySize]
add a comment `// snell use a special kdf function` in the previous line

2020-09-06 13:59 UTC, Dreamacro commented on component/snell/snell.go
> +	if version == Version2 {
snell v2 always write version1 (I don't know why, but it's)

2020-09-06 14:17 UTC, kamingchan commented on component/snell/snell.go
> +	if version == Version2 {
Fine. Both version1 and version2 work on official snell server.

2020-09-20 16:33 UTC, merged

2020-09-20 16:33 UTC, Dreamacro commented
Add pool for version 2, thanks for your contribution

2020-10-09 02:47 UTC, itspig commented
请问配置文件是snell节点加
version: 2 
就可以变成 v2 版本了吗？