Feature: Adds Plain TCP Redirect Outbound
Dreamacro/clash pull request #954
Opened 2020-09-06 18:12 UTC by mayanez

Hi,

Cool project! I'm not sure what the proper contribution guidelines are so let me know if I should modify anything.

This add a simple TCP redirection outbound. This is the same functionality as the `redirect` in V2Ray's `freedom` [protocol](https://www.v2ray.com/en/configuration/protocols/freedom.html). For example, it can be used to redirect traffic to different gateways on a network.

The same functionality can be implemented using `sockopt` mark/tags, but since it differs depending on the Firewall it might be useful for this to be included as part of Clash. I have yet to measure the `sockopt` mark option's performance, but I suspect it might be better. Given that it might make sense to eventually continue with PR https://github.com/Dreamacro/clash/pull/162 and add the ability to mark each outbound with its own `SO_MARK`.

2020-09-07 09:33 UTC, Dreamacro commented
Can you elaborate on the specific usage scenarios of `redirect`? I don't understand which scenario this is used in.

2020-09-07 16:35 UTC, mayanez commented
Sure, I’ll start with my use case. I’m using it to redirect traffic to different gateways on my internal network. These gateways are connected to different VPN endpoints effectively allowing me to split tunnel traffic.

As for other use-cases, the redirect adds an additional layer of abstraction to push the tunneling of traffic to other nodes/programs (eg. Wireguard, OpenVPN, etc) with Clash doing rule based routing by URLs etc. Put simply, it makes Clash a SNI based router. What makes this setup super powerful is the useful lists available for Clash.

2020-09-09 03:41 UTC, Dreamacro commented
> As for other use-cases, the redirect adds an additional layer of abstraction to push the tunneling of traffic to other nodes/programs (eg. Wireguard, OpenVPN, etc) with Clash doing rule-based routing by URLs, etc.

The core of the proxy client is how it receives traffic (i.e., Inbound). There are several types of traffic that clash currently receives: HTTP, Socks5, Redir, and TUN (closed source implementation). There are some problems with Redir and TUN (i.e., forcing traffic through iptable).

When using these two types, you usually need to specify `interface-name`, and all `Proxy`s will be forced to make requests through this interface. The VPN implementation is via TUN (on macOS), so this type is likely to cause problems in both modes.

I'm not a native English speaker, so I hope you understand what I'm saying.

2020-09-09 05:27 UTC, mayanez commented
No worries, I think I followed. 

Correct me if I'm wrong, but this is my current understanding. 

The `interface-name` is useful (1) when you are running on the same host and (2) when you want to send **all** your outbound connections via the specific interface. That is, the `interface-name` feature does **not** allow you to route individual rules via different interfaces or across different machines.  For example, you cannot do this:
```
               eth0     +----------------+
         +------------->+ VPN Provider 1 |
    +---------+         +----------------+
    |  Clash  |
    +---------+         +----------------+
         +------------->+ VPN Provider 2 |
               eth1     +----------------+
```


The TCP redirect I'm proposing allows you to route rules individually allowing you what I described above via `iptables`. 

Additionally, the machine that is running `clash` does not need to be the same one that tunnels the traffic. For example, a separate machine with a different OS can be setup to transparently tunnel data through a VPN. 
```
url: google.com
      10.0.0.10    +---------+    +----------------+
    +------------->+ Gateway +----> VPN Provider 1 |
+-------+          +---------+    +----------------+
| Clash |
+-------+          +---------+    +----------------+
    +------------->+ Gateway +----> VPN Provider 2 |
    url: bing.com  +---------+    +----------------+
      10.0.0.20
```

Hopefully, the diagrams make the communication easier :smiley:

2020-09-09 12:42 UTC, Dreamacro commented
If what you want is the second diagram, it's has a question about your PR: the TCP redirect problem.

When you dial a TCP request, there are two tuples: (srcIP, srcPort) --> (dstIP, dstPort). In your implementation just dialing a TCP connection, the gateway is not clear to the receiver what you really want to request, and need a protocol to received (e.g. Socks5 or shadowsocks).

```
want to connect google.com
       +---------+                 +---------+
       |  clash  |  +----------->  | Gateway | Not sure where to connect(google.com missing).
       +---------+10.10.10.10:1234 +---------+

```

2020-09-09 15:47 UTC, Dreamacro commented
Let me say what I have met (which may not be the same but is very similar).
1. the company needs to install a complicated application to connect to the VPN (the company's domain is `*.example.com`)
2. install the application in the virtual machine (10.10.10.10) and connect to the VPN so that the virtual machine can connect to `*.example.com`
3. run a clash in the virtual machine
```yaml
# two line to start a socks5 server
socks-port: 7890
allow-lan: true
```
4. run another clash on host.
```yaml
proxies:
    - name: socks5
      server: 10.10.10.10
      port: 7890
rules:
  - DOMAIN-SUFFIX,example.com,socks5
```

2020-09-09 22:58 UTC, mayanez commented
I think you're totally right for the second scenario as you wouldn't be able to NAT traffic back.

However, you can still do the first scenario. Actually, it's simpler to use `SO_MARK`. Therefore I've gone ahead and added that. Let me know if the implementation looks good. I am still trying to learn the codebase and go at the same time.

You can set the `socket-mark` globally in the config so it applies to `DIRECT`. 

You can also add `socket-mark` to each proxy, for example:
```
proxies:
  - name: "ssr"
    type: ssr
    socket-mark: 10
```

You can also now create multiple "direct" type proxies which is the same as "DIRECT", but you can define them with different `socket-mark`.
```
proxies:
  - name: "direct10"
    type: direct
    socket-mark: 10
```

With the `SO_MARK` then you can freely route traffic to different interfaces etc.

 Any thoughts?

2020-09-10 02:30 UTC, Dreamacro commented
But SO_MARK only works on Linux. macOS and Windows don't support it. I think `interface-name` is the best solution. Now `interface-name` is implemented via local-address, but I'm going to use syscall for macOS and Linux.

2020-09-10 02:57 UTC, mayanez commented
I think it's beneficial to add `SO_MARK` support even if it's just for Linux as it adds flexibility when it comes to writing `iptables` rules. 

For multi-platform support, I agree that extending `interface-name` per proxy is a good solution.

2020-09-10 14:35 UTC, mayanez commented
I went ahead and added the `interface-name` support for both Linux and macOS. I don't have a Mac to verify, but it seems to be the right system call. 

Let me know if are able to verify it.

2020-09-11 05:30 UTC, mayanez commented
> If what you want is the second diagram, it's has a question about your PR: the TCP redirect problem.
> 
> When you dial a TCP request, there are two tuples: (srcIP, srcPort) --> (dstIP, dstPort). In your implementation just dialing a TCP connection, the gateway is not clear to the receiver what you really want to request, and need a protocol to received (e.g. Socks5 or shadowsocks).
> 
> ```
> want to connect google.com
>        +---------+                 +---------+
>        |  clash  |  +----------->  | Gateway | Not sure where to connect(google.com missing).
>        +---------+10.10.10.10:1234 +---------+
> ```

After some research, it seems there is a solution to support this scenario (see the [HAProxy Protocol RFC](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt)). Not sure if it's something you'd eventually be interested in, but I will add it here for future reference.

2020-10-04 06:37 UTC, Dreamacro requested changes
Sorry for not checking this pr in a while, it's been a busy time. Here are a few of the tiny problems I found

2020-10-04 06:37 UTC, Dreamacro commented on adapters/outbound/shadowsocks.go
> +	c, err := dialer.DialContext(ctx, "tcp", ss.addr, dialer.DialOptions{SocketMark: ss.SocketMark(), Interface: ss.Interface()})
It seems that you're the only handling with the TCP-related parts, but there are some proxies that contain UDP parts (shadowsocks, socks5, etc.)

2020-10-04 06:37 UTC, Dreamacro commented on common/sockopt/sobind_darwin.go
> +	"github.com/Dreamacro/clash/log"
In this project, import split 3 parts: std, internal and third party, so it's better to format with

```go
import (
  // std

  // internal

  // third party
)
```

2020-10-04 06:37 UTC, Dreamacro commented on common/sockopt/sobind_darwin.go
> +				log.Errorln("Sockopt IP_BOUND_IP error: %s", err)
Previously, clash logging followed these rules. If it affects clash itself, the log level is `error`; if it doesn't affect clash itself, but there is an error, the log level is `warning`.

2020-10-04 06:37 UTC, Dreamacro commented on component/dialer/dialer.go
> +			markint, err := strconv.Atoi(opts[0].SocketMark)
what if `DialOptions` has two options?

2020-10-09 16:55 UTC, mayanez commented on adapters/outbound/shadowsocks.go
> +	c, err := dialer.DialContext(ctx, "tcp", ss.addr, dialer.DialOptions{SocketMark: ss.SocketMark(), Interface: ss.Interface()})
Got it. I will look into the UDP parts as well.

2020-10-09 16:56 UTC, mayanez commented on component/dialer/dialer.go
> +			markint, err := strconv.Atoi(opts[0].SocketMark)
This can definitely be changed to account for an arbitrary amount of options.

2020-10-20 11:13 UTC, Dreamacro commented
In order to make as small a change as possible (compared to this PR), I'm going to write a commit first to add the Linux and macOS syscall binding to the interface.

2021-06-15 12:04 UTC, Dreamacro commented
Sorry for the long time without reply, now I have enough time and energy to complete this feature request. I want to know if you still have the intention to complete this pr? If not, I'll finish this pr. I'll rebase to the latest code first

2021-08-21 01:48 UTC, closed without merging