Feature: support domain in fallback filter
Dreamacro/clash pull request #964
Opened 2020-09-13 20:11 UTC by MelvinTo

Sometimes domain (e.g. google.com) is resolved to a random IP address in China, the current clash will return the IP from standard nameservers directly, which is not right.

This new config is to always return the result of fallback nameservers if domain or domain suffix is matched.

Fallback Config Example:

```
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
    domain:
      - google.com
      - facebook.com
```

2020-09-17 02:56 UTC, Dreamacro commented
But the domain match timing is different from geoip and ipcidr. It should be resolved by fallback only

2020-09-17 03:35 UTC, MelvinTo commented
Agree. Let me check code

2020-09-18 03:19 UTC, MelvinTo commented
code updated

2020-09-25 16:43 UTC, Dreamacro reviewed
sorry for the late, here are some of my thoughts.

2020-09-25 16:43 UTC, Dreamacro commented on dns/filters.go
> +type domainFilter struct {
Why not use "github.com/Dreamacro/clash/component/trie"?

2020-09-25 16:43 UTC, Dreamacro commented on dns/resolver.go
> +func (r *Resolver) fallbackExchange(m *D.Msg) (msg *D.Msg, err error) {
maybe change this function name to `ipExchange`, then adding a `shouldQueryFallbackOnly` logic seems better?

2020-09-25 16:43 UTC, Dreamacro commented on dns/resolver.go
> +	for _, question := range msg.Question {
just handle msg.Question[0] is enough

2020-09-27 06:38 UTC, MelvinTo commented
updated, please review

2020-09-27 06:40 UTC, MelvinTo commented
one issue is how to combine *.google.com and google.com with trie? now the config looks redundant.

2020-09-27 06:53 UTC, Dreamacro commented
> one issue is how to combine *.google.com and google.com with trie? now the config looks redundant.

`+.google.com`

2020-09-27 09:00 UTC, MelvinTo commented
> `+.google.com`

cool, example updated.

2020-09-27 13:20 UTC, Dreamacro requested changes

2020-09-27 13:20 UTC, Dreamacro commented on dns/resolver.go
> +	r.fallbackDomainFilters = fallbackDomainFilters
maybe we can leave `r.fallbackDomainFilters` nil when `len(config.FallbackFilter.Domain) == 0`

2020-09-27 13:20 UTC, Dreamacro commented on dns/resolver.go
>  	if r.fallback == nil {
if r.fallback == nil || len(r.fallbackDomainFilters) == 0 {}

2020-09-28 06:55 UTC, Loyalsoldier commented
I think it's better if support `rule-providers`.

2020-09-28 14:17 UTC, merged

2020-09-28 14:18 UTC, Dreamacro commented
@Loyalsoldier Not sure what the relationship between this pr and rule provider.

2020-09-28 14:18 UTC, Dreamacro commented
@MelvinTo Thanks for your hard work

2020-09-28 14:28 UTC, Loyalsoldier commented
> @Loyalsoldier Not sure what the relationship between this pr and rule provider.

I mean support `rule-providers` files in `fallback-filter` section so as not to specify domains and CIDR manually, which is inconvenient.

2020-09-28 14:59 UTC, Dreamacro commented
@Loyalsoldier The need for an external file or an external link depends on the number of ipcidr rules. IMO, fallback rules shouldn't be large, so maybe we should not spend too much time doing this.

2020-09-28 15:06 UTC, Loyalsoldier commented
Or to support an option like `force-remote-dns` in Surge to skip the DNS resolving process for domain type of rules and rule-set.